// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: gordon/runtime/v1/runtime.proto

package runtimev1

import (
	context "context"
	v1 "github.com/bnema/gordon/api/gordon/common/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuntimeService_ApplyCommand_FullMethodName               = "/gordon.runtime.v1.RuntimeService/ApplyCommand"
	RuntimeService_WatchActualState_FullMethodName           = "/gordon.runtime.v1.RuntimeService/WatchActualState"
	RuntimeService_GetHealth_FullMethodName                  = "/gordon.runtime.v1.RuntimeService/GetHealth"
	RuntimeService_ProbeEnvironment_FullMethodName           = "/gordon.runtime.v1.RuntimeService/ProbeEnvironment"
	RuntimeService_StreamLogs_FullMethodName                 = "/gordon.runtime.v1.RuntimeService/StreamLogs"
	RuntimeService_ListVolumes_FullMethodName                = "/gordon.runtime.v1.RuntimeService/ListVolumes"
	RuntimeService_RemoveVolume_FullMethodName               = "/gordon.runtime.v1.RuntimeService/RemoveVolume"
	RuntimeService_ListImages_FullMethodName                 = "/gordon.runtime.v1.RuntimeService/ListImages"
	RuntimeService_PruneImages_FullMethodName                = "/gordon.runtime.v1.RuntimeService/PruneImages"
	RuntimeService_RuntimeSelfUpdate_FullMethodName          = "/gordon.runtime.v1.RuntimeService/RuntimeSelfUpdate"
	RuntimeService_ApplyStandaloneService_FullMethodName     = "/gordon.runtime.v1.RuntimeService/ApplyStandaloneService"
	RuntimeService_RemoveStandaloneService_FullMethodName    = "/gordon.runtime.v1.RuntimeService/RemoveStandaloneService"
	RuntimeService_ListStandaloneServiceState_FullMethodName = "/gordon.runtime.v1.RuntimeService/ListStandaloneServiceState"
	RuntimeService_ReportEdgeDrain_FullMethodName            = "/gordon.runtime.v1.RuntimeService/ReportEdgeDrain"
	RuntimeService_PrepareEdgeDrain_FullMethodName           = "/gordon.runtime.v1.RuntimeService/PrepareEdgeDrain"
)

// RuntimeServiceClient is the client API for RuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RuntimeService is the narrow intent surface exposed by gordon-runtime.
// It must not expose raw Docker/Podman socket operations or full inspect data.
type RuntimeServiceClient interface {
	ApplyCommand(ctx context.Context, in *ApplyCommandRequest, opts ...grpc.CallOption) (*ApplyCommandResponse, error)
	WatchActualState(ctx context.Context, in *WatchActualStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActualStateSnapshot], error)
	GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error)
	// ProbeEnvironment returns only migration-safe facts. It never exposes a
	// socket path, engine configuration, raw daemon payload, or error details.
	ProbeEnvironment(ctx context.Context, in *ProbeEnvironmentRequest, opts ...grpc.CallOption) (*ProbeEnvironmentResponse, error)
	StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error)
	ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error)
	RemoveVolume(ctx context.Context, in *RemoveVolumeRequest, opts ...grpc.CallOption) (*v1.Ack, error)
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
	PruneImages(ctx context.Context, in *PruneImagesRequest, opts ...grpc.CallOption) (*PruneImagesResponse, error)
	RuntimeSelfUpdate(ctx context.Context, in *RuntimeSelfUpdateRequest, opts ...grpc.CallOption) (*ApplyCommandResponse, error)
	// ApplyStandaloneService realizes one sanitized standalone-service spec.
	// Resolved environment values are accepted only as apply input and are never
	// returned by this service.
	ApplyStandaloneService(ctx context.Context, in *ApplyStandaloneServiceRequest, opts ...grpc.CallOption) (*ApplyStandaloneServiceResponse, error)
	RemoveStandaloneService(ctx context.Context, in *RemoveStandaloneServiceRequest, opts ...grpc.CallOption) (*RemoveStandaloneServiceResponse, error)
	ListStandaloneServiceState(ctx context.Context, in *ListStandaloneServiceStateRequest, opts ...grpc.CallOption) (*ListStandaloneServiceStateResponse, error)
	// ReportEdgeDrain is called by gordon-control after gordon-edge reports that
	// a route generation has drained. Edge never calls runtime directly: edge
	// reports drain state to control, control validates generation and target,
	// then relays this acknowledgement to runtime. Runtime waits for this ack or
	// its configured drain timeout before stopping the old route container.
	ReportEdgeDrain(ctx context.Context, in *ReportEdgeDrainRequest, opts ...grpc.CallOption) (*v1.Ack, error)
	// PrepareEdgeDrain registers the exact control transition before edge
	// acknowledgement delivery. It is control-only and carries opaque data.
	PrepareEdgeDrain(ctx context.Context, in *PrepareEdgeDrainRequest, opts ...grpc.CallOption) (*v1.Ack, error)
}

type runtimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeServiceClient(cc grpc.ClientConnInterface) RuntimeServiceClient {
	return &runtimeServiceClient{cc}
}

func (c *runtimeServiceClient) ApplyCommand(ctx context.Context, in *ApplyCommandRequest, opts ...grpc.CallOption) (*ApplyCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyCommandResponse)
	err := c.cc.Invoke(ctx, RuntimeService_ApplyCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) WatchActualState(ctx context.Context, in *WatchActualStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActualStateSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RuntimeService_ServiceDesc.Streams[0], RuntimeService_WatchActualState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchActualStateRequest, ActualStateSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeService_WatchActualStateClient = grpc.ServerStreamingClient[ActualStateSnapshot]

func (c *runtimeServiceClient) GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHealthResponse)
	err := c.cc.Invoke(ctx, RuntimeService_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) ProbeEnvironment(ctx context.Context, in *ProbeEnvironmentRequest, opts ...grpc.CallOption) (*ProbeEnvironmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeEnvironmentResponse)
	err := c.cc.Invoke(ctx, RuntimeService_ProbeEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RuntimeService_ServiceDesc.Streams[1], RuntimeService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLogsRequest, LogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeService_StreamLogsClient = grpc.ServerStreamingClient[LogChunk]

func (c *runtimeServiceClient) ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVolumesResponse)
	err := c.cc.Invoke(ctx, RuntimeService_ListVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) RemoveVolume(ctx context.Context, in *RemoveVolumeRequest, opts ...grpc.CallOption) (*v1.Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Ack)
	err := c.cc.Invoke(ctx, RuntimeService_RemoveVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, RuntimeService_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) PruneImages(ctx context.Context, in *PruneImagesRequest, opts ...grpc.CallOption) (*PruneImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PruneImagesResponse)
	err := c.cc.Invoke(ctx, RuntimeService_PruneImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) RuntimeSelfUpdate(ctx context.Context, in *RuntimeSelfUpdateRequest, opts ...grpc.CallOption) (*ApplyCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyCommandResponse)
	err := c.cc.Invoke(ctx, RuntimeService_RuntimeSelfUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) ApplyStandaloneService(ctx context.Context, in *ApplyStandaloneServiceRequest, opts ...grpc.CallOption) (*ApplyStandaloneServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyStandaloneServiceResponse)
	err := c.cc.Invoke(ctx, RuntimeService_ApplyStandaloneService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) RemoveStandaloneService(ctx context.Context, in *RemoveStandaloneServiceRequest, opts ...grpc.CallOption) (*RemoveStandaloneServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveStandaloneServiceResponse)
	err := c.cc.Invoke(ctx, RuntimeService_RemoveStandaloneService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) ListStandaloneServiceState(ctx context.Context, in *ListStandaloneServiceStateRequest, opts ...grpc.CallOption) (*ListStandaloneServiceStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStandaloneServiceStateResponse)
	err := c.cc.Invoke(ctx, RuntimeService_ListStandaloneServiceState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) ReportEdgeDrain(ctx context.Context, in *ReportEdgeDrainRequest, opts ...grpc.CallOption) (*v1.Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Ack)
	err := c.cc.Invoke(ctx, RuntimeService_ReportEdgeDrain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) PrepareEdgeDrain(ctx context.Context, in *PrepareEdgeDrainRequest, opts ...grpc.CallOption) (*v1.Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Ack)
	err := c.cc.Invoke(ctx, RuntimeService_PrepareEdgeDrain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeServiceServer is the server API for RuntimeService service.
// All implementations must embed UnimplementedRuntimeServiceServer
// for forward compatibility.
//
// RuntimeService is the narrow intent surface exposed by gordon-runtime.
// It must not expose raw Docker/Podman socket operations or full inspect data.
type RuntimeServiceServer interface {
	ApplyCommand(context.Context, *ApplyCommandRequest) (*ApplyCommandResponse, error)
	WatchActualState(*WatchActualStateRequest, grpc.ServerStreamingServer[ActualStateSnapshot]) error
	GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error)
	// ProbeEnvironment returns only migration-safe facts. It never exposes a
	// socket path, engine configuration, raw daemon payload, or error details.
	ProbeEnvironment(context.Context, *ProbeEnvironmentRequest) (*ProbeEnvironmentResponse, error)
	StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogChunk]) error
	ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error)
	RemoveVolume(context.Context, *RemoveVolumeRequest) (*v1.Ack, error)
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	PruneImages(context.Context, *PruneImagesRequest) (*PruneImagesResponse, error)
	RuntimeSelfUpdate(context.Context, *RuntimeSelfUpdateRequest) (*ApplyCommandResponse, error)
	// ApplyStandaloneService realizes one sanitized standalone-service spec.
	// Resolved environment values are accepted only as apply input and are never
	// returned by this service.
	ApplyStandaloneService(context.Context, *ApplyStandaloneServiceRequest) (*ApplyStandaloneServiceResponse, error)
	RemoveStandaloneService(context.Context, *RemoveStandaloneServiceRequest) (*RemoveStandaloneServiceResponse, error)
	ListStandaloneServiceState(context.Context, *ListStandaloneServiceStateRequest) (*ListStandaloneServiceStateResponse, error)
	// ReportEdgeDrain is called by gordon-control after gordon-edge reports that
	// a route generation has drained. Edge never calls runtime directly: edge
	// reports drain state to control, control validates generation and target,
	// then relays this acknowledgement to runtime. Runtime waits for this ack or
	// its configured drain timeout before stopping the old route container.
	ReportEdgeDrain(context.Context, *ReportEdgeDrainRequest) (*v1.Ack, error)
	// PrepareEdgeDrain registers the exact control transition before edge
	// acknowledgement delivery. It is control-only and carries opaque data.
	PrepareEdgeDrain(context.Context, *PrepareEdgeDrainRequest) (*v1.Ack, error)
	mustEmbedUnimplementedRuntimeServiceServer()
}

// UnimplementedRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeServiceServer struct{}

func (UnimplementedRuntimeServiceServer) ApplyCommand(context.Context, *ApplyCommandRequest) (*ApplyCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyCommand not implemented")
}
func (UnimplementedRuntimeServiceServer) WatchActualState(*WatchActualStateRequest, grpc.ServerStreamingServer[ActualStateSnapshot]) error {
	return status.Error(codes.Unimplemented, "method WatchActualState not implemented")
}
func (UnimplementedRuntimeServiceServer) GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedRuntimeServiceServer) ProbeEnvironment(context.Context, *ProbeEnvironmentRequest) (*ProbeEnvironmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProbeEnvironment not implemented")
}
func (UnimplementedRuntimeServiceServer) StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedRuntimeServiceServer) ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVolumes not implemented")
}
func (UnimplementedRuntimeServiceServer) RemoveVolume(context.Context, *RemoveVolumeRequest) (*v1.Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveVolume not implemented")
}
func (UnimplementedRuntimeServiceServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedRuntimeServiceServer) PruneImages(context.Context, *PruneImagesRequest) (*PruneImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PruneImages not implemented")
}
func (UnimplementedRuntimeServiceServer) RuntimeSelfUpdate(context.Context, *RuntimeSelfUpdateRequest) (*ApplyCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RuntimeSelfUpdate not implemented")
}
func (UnimplementedRuntimeServiceServer) ApplyStandaloneService(context.Context, *ApplyStandaloneServiceRequest) (*ApplyStandaloneServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyStandaloneService not implemented")
}
func (UnimplementedRuntimeServiceServer) RemoveStandaloneService(context.Context, *RemoveStandaloneServiceRequest) (*RemoveStandaloneServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveStandaloneService not implemented")
}
func (UnimplementedRuntimeServiceServer) ListStandaloneServiceState(context.Context, *ListStandaloneServiceStateRequest) (*ListStandaloneServiceStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStandaloneServiceState not implemented")
}
func (UnimplementedRuntimeServiceServer) ReportEdgeDrain(context.Context, *ReportEdgeDrainRequest) (*v1.Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportEdgeDrain not implemented")
}
func (UnimplementedRuntimeServiceServer) PrepareEdgeDrain(context.Context, *PrepareEdgeDrainRequest) (*v1.Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareEdgeDrain not implemented")
}
func (UnimplementedRuntimeServiceServer) mustEmbedUnimplementedRuntimeServiceServer() {}
func (UnimplementedRuntimeServiceServer) testEmbeddedByValue()                        {}

// UnsafeRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeServiceServer will
// result in compilation errors.
type UnsafeRuntimeServiceServer interface {
	mustEmbedUnimplementedRuntimeServiceServer()
}

func RegisterRuntimeServiceServer(s grpc.ServiceRegistrar, srv RuntimeServiceServer) {
	// If the following call panics, it indicates UnimplementedRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuntimeService_ServiceDesc, srv)
}

func _RuntimeService_ApplyCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).ApplyCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_ApplyCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).ApplyCommand(ctx, req.(*ApplyCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_WatchActualState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchActualStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeServiceServer).WatchActualState(m, &grpc.GenericServerStream[WatchActualStateRequest, ActualStateSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeService_WatchActualStateServer = grpc.ServerStreamingServer[ActualStateSnapshot]

func _RuntimeService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).GetHealth(ctx, req.(*GetHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_ProbeEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).ProbeEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_ProbeEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).ProbeEnvironment(ctx, req.(*ProbeEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeServiceServer).StreamLogs(m, &grpc.GenericServerStream[StreamLogsRequest, LogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeService_StreamLogsServer = grpc.ServerStreamingServer[LogChunk]

func _RuntimeService_ListVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).ListVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_ListVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).ListVolumes(ctx, req.(*ListVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_RemoveVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).RemoveVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_RemoveVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).RemoveVolume(ctx, req.(*RemoveVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_PruneImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PruneImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).PruneImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_PruneImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).PruneImages(ctx, req.(*PruneImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_RuntimeSelfUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeSelfUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).RuntimeSelfUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_RuntimeSelfUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).RuntimeSelfUpdate(ctx, req.(*RuntimeSelfUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_ApplyStandaloneService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyStandaloneServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).ApplyStandaloneService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_ApplyStandaloneService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).ApplyStandaloneService(ctx, req.(*ApplyStandaloneServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_RemoveStandaloneService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveStandaloneServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).RemoveStandaloneService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_RemoveStandaloneService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).RemoveStandaloneService(ctx, req.(*RemoveStandaloneServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_ListStandaloneServiceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStandaloneServiceStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).ListStandaloneServiceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_ListStandaloneServiceState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).ListStandaloneServiceState(ctx, req.(*ListStandaloneServiceStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_ReportEdgeDrain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportEdgeDrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).ReportEdgeDrain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_ReportEdgeDrain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).ReportEdgeDrain(ctx, req.(*ReportEdgeDrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_PrepareEdgeDrain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareEdgeDrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).PrepareEdgeDrain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_PrepareEdgeDrain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).PrepareEdgeDrain(ctx, req.(*PrepareEdgeDrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuntimeService_ServiceDesc is the grpc.ServiceDesc for RuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gordon.runtime.v1.RuntimeService",
	HandlerType: (*RuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyCommand",
			Handler:    _RuntimeService_ApplyCommand_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _RuntimeService_GetHealth_Handler,
		},
		{
			MethodName: "ProbeEnvironment",
			Handler:    _RuntimeService_ProbeEnvironment_Handler,
		},
		{
			MethodName: "ListVolumes",
			Handler:    _RuntimeService_ListVolumes_Handler,
		},
		{
			MethodName: "RemoveVolume",
			Handler:    _RuntimeService_RemoveVolume_Handler,
		},
		{
			MethodName: "ListImages",
			Handler:    _RuntimeService_ListImages_Handler,
		},
		{
			MethodName: "PruneImages",
			Handler:    _RuntimeService_PruneImages_Handler,
		},
		{
			MethodName: "RuntimeSelfUpdate",
			Handler:    _RuntimeService_RuntimeSelfUpdate_Handler,
		},
		{
			MethodName: "ApplyStandaloneService",
			Handler:    _RuntimeService_ApplyStandaloneService_Handler,
		},
		{
			MethodName: "RemoveStandaloneService",
			Handler:    _RuntimeService_RemoveStandaloneService_Handler,
		},
		{
			MethodName: "ListStandaloneServiceState",
			Handler:    _RuntimeService_ListStandaloneServiceState_Handler,
		},
		{
			MethodName: "ReportEdgeDrain",
			Handler:    _RuntimeService_ReportEdgeDrain_Handler,
		},
		{
			MethodName: "PrepareEdgeDrain",
			Handler:    _RuntimeService_PrepareEdgeDrain_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchActualState",
			Handler:       _RuntimeService_WatchActualState_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _RuntimeService_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gordon/runtime/v1/runtime.proto",
}
