version: 2

before:
  hooks:

release:
  draft: true

builds:
  - id: "gordon"
    main: ./main.go
    binary: gordon
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

# Docker builds disabled for v2.0.0 release (will add back with proper buildx setup)
# dockers:
# docker_manifests:

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
