before:
  hooks:
    - go mod tidy
release:
  draft: true
builds:
  - id: "gordon"
    main: ./cmd/cli/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.build={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

dockers:
  - image_templates:
      - "ghcr.io/bnema/gordon:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/bnema/gordon"
    extra_files:
      - .iscontainer
  - image_templates:
      - "ghcr.io/bnema/gordon:{{ .Version }}-arm64"
    use: buildx
    dockerfile: Dockerfile
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/bnema/gordon"
    extra_files:
      - .iscontainer
docker_manifests:
  - name_template: "ghcr.io/bnema/gordon:{{ .Version }}"
    image_templates:
      - "ghcr.io/bnema/gordon:{{ .Version }}-amd64"
      - "ghcr.io/bnema/gordon:{{ .Version }}-arm64"
  - name_template: "ghcr.io/bnema/gordon:latest"
    image_templates:
      - "ghcr.io/bnema/gordon:{{ .Version }}-amd64"
      - "ghcr.io/bnema/gordon:{{ .Version }}-arm64"
    create_flags: ["--amend"]

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"