// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bnema/gordon/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTrafficStatusService creates a new instance of MockTrafficStatusService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrafficStatusService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrafficStatusService {
	mock := &MockTrafficStatusService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTrafficStatusService is an autogenerated mock type for the TrafficStatusService type
type MockTrafficStatusService struct {
	mock.Mock
}

type MockTrafficStatusService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrafficStatusService) EXPECT() *MockTrafficStatusService_Expecter {
	return &MockTrafficStatusService_Expecter{mock: &_m.Mock}
}

// Status provides a mock function for the type MockTrafficStatusService
func (_mock *MockTrafficStatusService) Status() domain.TrafficStatus {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 domain.TrafficStatus
	if returnFunc, ok := ret.Get(0).(func() domain.TrafficStatus); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(domain.TrafficStatus)
	}
	return r0
}

// MockTrafficStatusService_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockTrafficStatusService_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *MockTrafficStatusService_Expecter) Status() *MockTrafficStatusService_Status_Call {
	return &MockTrafficStatusService_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *MockTrafficStatusService_Status_Call) Run(run func()) *MockTrafficStatusService_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTrafficStatusService_Status_Call) Return(trafficStatus domain.TrafficStatus) *MockTrafficStatusService_Status_Call {
	_c.Call.Return(trafficStatus)
	return _c
}

func (_c *MockTrafficStatusService_Status_Call) RunAndReturn(run func() domain.TrafficStatus) *MockTrafficStatusService_Status_Call {
	_c.Call.Return(run)
	return _c
}
