// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDeployCoordinator creates a new instance of MockDeployCoordinator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeployCoordinator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeployCoordinator {
	mock := &MockDeployCoordinator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeployCoordinator is an autogenerated mock type for the DeployCoordinator type.
type MockDeployCoordinator struct {
	mock.Mock
}

type MockDeployCoordinator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeployCoordinator) EXPECT() *MockDeployCoordinator_Expecter {
	return &MockDeployCoordinator_Expecter{mock: &_m.Mock}
}

// ClearDeployEventSuppression provides a mock function for the type MockDeployCoordinator.
func (_mock *MockDeployCoordinator) ClearDeployEventSuppression(imageName string) {
	_mock.Called(imageName)
}

// MockDeployCoordinator_ClearDeployEventSuppression_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearDeployEventSuppression'.
type MockDeployCoordinator_ClearDeployEventSuppression_Call struct {
	*mock.Call
}

// ClearDeployEventSuppression is a helper method to define mock.On call.
//   - imageName string
func (_e *MockDeployCoordinator_Expecter) ClearDeployEventSuppression(imageName interface{}) *MockDeployCoordinator_ClearDeployEventSuppression_Call {
	return &MockDeployCoordinator_ClearDeployEventSuppression_Call{Call: _e.mock.On("ClearDeployEventSuppression", imageName)}
}

func (_c *MockDeployCoordinator_ClearDeployEventSuppression_Call) Run(run func(imageName string)) *MockDeployCoordinator_ClearDeployEventSuppression_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(arg0)
	})
	return _c
}

func (_c *MockDeployCoordinator_ClearDeployEventSuppression_Call) Return() *MockDeployCoordinator_ClearDeployEventSuppression_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDeployCoordinator_ClearDeployEventSuppression_Call) RunAndReturn(run func(imageName string)) *MockDeployCoordinator_ClearDeployEventSuppression_Call {
	_c.Run(run)
	return _c
}

// SuppressDeployEvent provides a mock function for the type MockDeployCoordinator.
func (_mock *MockDeployCoordinator) SuppressDeployEvent(imageName string) {
	_mock.Called(imageName)
}

// MockDeployCoordinator_SuppressDeployEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuppressDeployEvent'.
type MockDeployCoordinator_SuppressDeployEvent_Call struct {
	*mock.Call
}

// SuppressDeployEvent is a helper method to define mock.On call.
//   - imageName string
func (_e *MockDeployCoordinator_Expecter) SuppressDeployEvent(imageName interface{}) *MockDeployCoordinator_SuppressDeployEvent_Call {
	return &MockDeployCoordinator_SuppressDeployEvent_Call{Call: _e.mock.On("SuppressDeployEvent", imageName)}
}

func (_c *MockDeployCoordinator_SuppressDeployEvent_Call) Run(run func(imageName string)) *MockDeployCoordinator_SuppressDeployEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(arg0)
	})
	return _c
}

func (_c *MockDeployCoordinator_SuppressDeployEvent_Call) Return() *MockDeployCoordinator_SuppressDeployEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDeployCoordinator_SuppressDeployEvent_Call) RunAndReturn(run func(imageName string)) *MockDeployCoordinator_SuppressDeployEvent_Call {
	_c.Run(run)
	return _c
}
