// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCAInfoService creates a new instance of MockCAInfoService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCAInfoService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCAInfoService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockCAInfoService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockCAInfoService is an autogenerated mock type for the CAInfoService type
type MockCAInfoService struct {
	mock.Mock
}

type MockCAInfoService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCAInfoService) EXPECT() *MockCAInfoService_Expecter {
	return &MockCAInfoService_Expecter{mock: &_m.Mock}
}

// IntermediateExpiresAt provides a mock function for the type MockCAInfoService
func (_mock *MockCAInfoService) IntermediateExpiresAt() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IntermediateExpiresAt")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockCAInfoService_IntermediateExpiresAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IntermediateExpiresAt'
type MockCAInfoService_IntermediateExpiresAt_Call struct {
	*mock.Call
}

// IntermediateExpiresAt is a helper method to define mock.On call
func (_e *MockCAInfoService_Expecter) IntermediateExpiresAt() *MockCAInfoService_IntermediateExpiresAt_Call {
	return &MockCAInfoService_IntermediateExpiresAt_Call{Call: _e.mock.On("IntermediateExpiresAt")}
}

func (_c *MockCAInfoService_IntermediateExpiresAt_Call) Run(run func()) *MockCAInfoService_IntermediateExpiresAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCAInfoService_IntermediateExpiresAt_Call) Return(time1 time.Time) *MockCAInfoService_IntermediateExpiresAt_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockCAInfoService_IntermediateExpiresAt_Call) RunAndReturn(run func() time.Time) *MockCAInfoService_IntermediateExpiresAt_Call {
	_c.Call.Return(run)
	return _c
}

// RootCertificate provides a mock function for the type MockCAInfoService
func (_mock *MockCAInfoService) RootCertificate() []byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RootCertificate")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// MockCAInfoService_RootCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RootCertificate'
type MockCAInfoService_RootCertificate_Call struct {
	*mock.Call
}

// RootCertificate is a helper method to define mock.On call
func (_e *MockCAInfoService_Expecter) RootCertificate() *MockCAInfoService_RootCertificate_Call {
	return &MockCAInfoService_RootCertificate_Call{Call: _e.mock.On("RootCertificate")}
}

func (_c *MockCAInfoService_RootCertificate_Call) Run(run func()) *MockCAInfoService_RootCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCAInfoService_RootCertificate_Call) Return(bytes []byte) *MockCAInfoService_RootCertificate_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *MockCAInfoService_RootCertificate_Call) RunAndReturn(run func() []byte) *MockCAInfoService_RootCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// RootCommonName provides a mock function for the type MockCAInfoService
func (_mock *MockCAInfoService) RootCommonName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RootCommonName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCAInfoService_RootCommonName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RootCommonName'
type MockCAInfoService_RootCommonName_Call struct {
	*mock.Call
}

// RootCommonName is a helper method to define mock.On call
func (_e *MockCAInfoService_Expecter) RootCommonName() *MockCAInfoService_RootCommonName_Call {
	return &MockCAInfoService_RootCommonName_Call{Call: _e.mock.On("RootCommonName")}
}

func (_c *MockCAInfoService_RootCommonName_Call) Run(run func()) *MockCAInfoService_RootCommonName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCAInfoService_RootCommonName_Call) Return(s string) *MockCAInfoService_RootCommonName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCAInfoService_RootCommonName_Call) RunAndReturn(run func() string) *MockCAInfoService_RootCommonName_Call {
	_c.Call.Return(run)
	return _c
}

// RootFingerprint provides a mock function for the type MockCAInfoService
func (_mock *MockCAInfoService) RootFingerprint() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RootFingerprint")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCAInfoService_RootFingerprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RootFingerprint'
type MockCAInfoService_RootFingerprint_Call struct {
	*mock.Call
}

// RootFingerprint is a helper method to define mock.On call
func (_e *MockCAInfoService_Expecter) RootFingerprint() *MockCAInfoService_RootFingerprint_Call {
	return &MockCAInfoService_RootFingerprint_Call{Call: _e.mock.On("RootFingerprint")}
}

func (_c *MockCAInfoService_RootFingerprint_Call) Run(run func()) *MockCAInfoService_RootFingerprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCAInfoService_RootFingerprint_Call) Return(s string) *MockCAInfoService_RootFingerprint_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCAInfoService_RootFingerprint_Call) RunAndReturn(run func() string) *MockCAInfoService_RootFingerprint_Call {
	_c.Call.Return(run)
	return _c
}
