// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/bnema/gordon/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHealthService creates a new instance of MockHealthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthService {
	mock := &MockHealthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHealthService is an autogenerated mock type for the HealthService type
type MockHealthService struct {
	mock.Mock
}

type MockHealthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthService) EXPECT() *MockHealthService_Expecter {
	return &MockHealthService_Expecter{mock: &_m.Mock}
}

// CheckAllRoutes provides a mock function for the type MockHealthService
func (_mock *MockHealthService) CheckAllRoutes(ctx context.Context) map[string]*domain.RouteHealth {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckAllRoutes")
	}

	var r0 map[string]*domain.RouteHealth
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]*domain.RouteHealth); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*domain.RouteHealth)
		}
	}
	return r0
}

// MockHealthService_CheckAllRoutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckAllRoutes'
type MockHealthService_CheckAllRoutes_Call struct {
	*mock.Call
}

// CheckAllRoutes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHealthService_Expecter) CheckAllRoutes(ctx interface{}) *MockHealthService_CheckAllRoutes_Call {
	return &MockHealthService_CheckAllRoutes_Call{Call: _e.mock.On("CheckAllRoutes", ctx)}
}

func (_c *MockHealthService_CheckAllRoutes_Call) Run(run func(ctx context.Context)) *MockHealthService_CheckAllRoutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHealthService_CheckAllRoutes_Call) Return(stringToRouteHealth map[string]*domain.RouteHealth) *MockHealthService_CheckAllRoutes_Call {
	_c.Call.Return(stringToRouteHealth)
	return _c
}

func (_c *MockHealthService_CheckAllRoutes_Call) RunAndReturn(run func(ctx context.Context) map[string]*domain.RouteHealth) *MockHealthService_CheckAllRoutes_Call {
	_c.Call.Return(run)
	return _c
}

// CheckRoute provides a mock function for the type MockHealthService
func (_mock *MockHealthService) CheckRoute(ctx context.Context, route domain.Route) *domain.RouteHealth {
	ret := _mock.Called(ctx, route)

	if len(ret) == 0 {
		panic("no return value specified for CheckRoute")
	}

	var r0 *domain.RouteHealth
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Route) *domain.RouteHealth); ok {
		r0 = returnFunc(ctx, route)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RouteHealth)
		}
	}
	return r0
}

// MockHealthService_CheckRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckRoute'
type MockHealthService_CheckRoute_Call struct {
	*mock.Call
}

// CheckRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - route domain.Route
func (_e *MockHealthService_Expecter) CheckRoute(ctx interface{}, route interface{}) *MockHealthService_CheckRoute_Call {
	return &MockHealthService_CheckRoute_Call{Call: _e.mock.On("CheckRoute", ctx, route)}
}

func (_c *MockHealthService_CheckRoute_Call) Run(run func(ctx context.Context, route domain.Route)) *MockHealthService_CheckRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Route
		if args[1] != nil {
			arg1 = args[1].(domain.Route)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHealthService_CheckRoute_Call) Return(routeHealth *domain.RouteHealth) *MockHealthService_CheckRoute_Call {
	_c.Call.Return(routeHealth)
	return _c
}

func (_c *MockHealthService_CheckRoute_Call) RunAndReturn(run func(ctx context.Context, route domain.Route) *domain.RouteHealth) *MockHealthService_CheckRoute_Call {
	_c.Call.Return(run)
	return _c
}
