// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"gordon/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigService creates a new instance of MockConfigService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigService {
	mock := &MockConfigService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigService is an autogenerated mock type for the ConfigService type
type MockConfigService struct {
	mock.Mock
}

type MockConfigService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigService) EXPECT() *MockConfigService_Expecter {
	return &MockConfigService_Expecter{mock: &_m.Mock}
}

// AddRoute provides a mock function for the type MockConfigService
func (_mock *MockConfigService) AddRoute(ctx context.Context, route domain.Route) error {
	ret := _mock.Called(ctx, route)

	if len(ret) == 0 {
		panic("no return value specified for AddRoute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Route) error); ok {
		r0 = returnFunc(ctx, route)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigService_AddRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRoute'
type MockConfigService_AddRoute_Call struct {
	*mock.Call
}

// AddRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - route domain.Route
func (_e *MockConfigService_Expecter) AddRoute(ctx interface{}, route interface{}) *MockConfigService_AddRoute_Call {
	return &MockConfigService_AddRoute_Call{Call: _e.mock.On("AddRoute", ctx, route)}
}

func (_c *MockConfigService_AddRoute_Call) Run(run func(ctx context.Context, route domain.Route)) *MockConfigService_AddRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Route
		if args[1] != nil {
			arg1 = args[1].(domain.Route)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigService_AddRoute_Call) Return(err error) *MockConfigService_AddRoute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigService_AddRoute_Call) RunAndReturn(run func(ctx context.Context, route domain.Route) error) *MockConfigService_AddRoute_Call {
	_c.Call.Return(run)
	return _c
}

// GetDataDir provides a mock function for the type MockConfigService
func (_mock *MockConfigService) GetDataDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDataDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfigService_GetDataDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDataDir'
type MockConfigService_GetDataDir_Call struct {
	*mock.Call
}

// GetDataDir is a helper method to define mock.On call
func (_e *MockConfigService_Expecter) GetDataDir() *MockConfigService_GetDataDir_Call {
	return &MockConfigService_GetDataDir_Call{Call: _e.mock.On("GetDataDir")}
}

func (_c *MockConfigService_GetDataDir_Call) Run(run func()) *MockConfigService_GetDataDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigService_GetDataDir_Call) Return(s string) *MockConfigService_GetDataDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfigService_GetDataDir_Call) RunAndReturn(run func() string) *MockConfigService_GetDataDir_Call {
	_c.Call.Return(run)
	return _c
}

// GetExternalRoutes provides a mock function for the type MockConfigService
func (_mock *MockConfigService) GetExternalRoutes() map[string]string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetExternalRoutes")
	}

	var r0 map[string]string
	if returnFunc, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	return r0
}

// MockConfigService_GetExternalRoutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExternalRoutes'
type MockConfigService_GetExternalRoutes_Call struct {
	*mock.Call
}

// GetExternalRoutes is a helper method to define mock.On call
func (_e *MockConfigService_Expecter) GetExternalRoutes() *MockConfigService_GetExternalRoutes_Call {
	return &MockConfigService_GetExternalRoutes_Call{Call: _e.mock.On("GetExternalRoutes")}
}

func (_c *MockConfigService_GetExternalRoutes_Call) Run(run func()) *MockConfigService_GetExternalRoutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigService_GetExternalRoutes_Call) Return(stringToString map[string]string) *MockConfigService_GetExternalRoutes_Call {
	_c.Call.Return(stringToString)
	return _c
}

func (_c *MockConfigService_GetExternalRoutes_Call) RunAndReturn(run func() map[string]string) *MockConfigService_GetExternalRoutes_Call {
	_c.Call.Return(run)
	return _c
}

// GetNetworkPrefix provides a mock function for the type MockConfigService
func (_mock *MockConfigService) GetNetworkPrefix() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNetworkPrefix")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfigService_GetNetworkPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNetworkPrefix'
type MockConfigService_GetNetworkPrefix_Call struct {
	*mock.Call
}

// GetNetworkPrefix is a helper method to define mock.On call
func (_e *MockConfigService_Expecter) GetNetworkPrefix() *MockConfigService_GetNetworkPrefix_Call {
	return &MockConfigService_GetNetworkPrefix_Call{Call: _e.mock.On("GetNetworkPrefix")}
}

func (_c *MockConfigService_GetNetworkPrefix_Call) Run(run func()) *MockConfigService_GetNetworkPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigService_GetNetworkPrefix_Call) Return(s string) *MockConfigService_GetNetworkPrefix_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfigService_GetNetworkPrefix_Call) RunAndReturn(run func() string) *MockConfigService_GetNetworkPrefix_Call {
	_c.Call.Return(run)
	return _c
}

// GetRegistryDomain provides a mock function for the type MockConfigService
func (_mock *MockConfigService) GetRegistryDomain() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRegistryDomain")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfigService_GetRegistryDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegistryDomain'
type MockConfigService_GetRegistryDomain_Call struct {
	*mock.Call
}

// GetRegistryDomain is a helper method to define mock.On call
func (_e *MockConfigService_Expecter) GetRegistryDomain() *MockConfigService_GetRegistryDomain_Call {
	return &MockConfigService_GetRegistryDomain_Call{Call: _e.mock.On("GetRegistryDomain")}
}

func (_c *MockConfigService_GetRegistryDomain_Call) Run(run func()) *MockConfigService_GetRegistryDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigService_GetRegistryDomain_Call) Return(s string) *MockConfigService_GetRegistryDomain_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfigService_GetRegistryDomain_Call) RunAndReturn(run func() string) *MockConfigService_GetRegistryDomain_Call {
	_c.Call.Return(run)
	return _c
}

// GetRegistryPort provides a mock function for the type MockConfigService
func (_mock *MockConfigService) GetRegistryPort() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRegistryPort")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockConfigService_GetRegistryPort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegistryPort'
type MockConfigService_GetRegistryPort_Call struct {
	*mock.Call
}

// GetRegistryPort is a helper method to define mock.On call
func (_e *MockConfigService_Expecter) GetRegistryPort() *MockConfigService_GetRegistryPort_Call {
	return &MockConfigService_GetRegistryPort_Call{Call: _e.mock.On("GetRegistryPort")}
}

func (_c *MockConfigService_GetRegistryPort_Call) Run(run func()) *MockConfigService_GetRegistryPort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigService_GetRegistryPort_Call) Return(n int) *MockConfigService_GetRegistryPort_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockConfigService_GetRegistryPort_Call) RunAndReturn(run func() int) *MockConfigService_GetRegistryPort_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoutes provides a mock function for the type MockConfigService
func (_mock *MockConfigService) GetRoutes(ctx context.Context) []domain.Route {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRoutes")
	}

	var r0 []domain.Route
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Route); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Route)
		}
	}
	return r0
}

// MockConfigService_GetRoutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoutes'
type MockConfigService_GetRoutes_Call struct {
	*mock.Call
}

// GetRoutes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConfigService_Expecter) GetRoutes(ctx interface{}) *MockConfigService_GetRoutes_Call {
	return &MockConfigService_GetRoutes_Call{Call: _e.mock.On("GetRoutes", ctx)}
}

func (_c *MockConfigService_GetRoutes_Call) Run(run func(ctx context.Context)) *MockConfigService_GetRoutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigService_GetRoutes_Call) Return(routes []domain.Route) *MockConfigService_GetRoutes_Call {
	_c.Call.Return(routes)
	return _c
}

func (_c *MockConfigService_GetRoutes_Call) RunAndReturn(run func(ctx context.Context) []domain.Route) *MockConfigService_GetRoutes_Call {
	_c.Call.Return(run)
	return _c
}

// GetServerPort provides a mock function for the type MockConfigService
func (_mock *MockConfigService) GetServerPort() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetServerPort")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockConfigService_GetServerPort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServerPort'
type MockConfigService_GetServerPort_Call struct {
	*mock.Call
}

// GetServerPort is a helper method to define mock.On call
func (_e *MockConfigService_Expecter) GetServerPort() *MockConfigService_GetServerPort_Call {
	return &MockConfigService_GetServerPort_Call{Call: _e.mock.On("GetServerPort")}
}

func (_c *MockConfigService_GetServerPort_Call) Run(run func()) *MockConfigService_GetServerPort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigService_GetServerPort_Call) Return(n int) *MockConfigService_GetServerPort_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockConfigService_GetServerPort_Call) RunAndReturn(run func() int) *MockConfigService_GetServerPort_Call {
	_c.Call.Return(run)
	return _c
}

// IsAutoRouteEnabled provides a mock function for the type MockConfigService
func (_mock *MockConfigService) IsAutoRouteEnabled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsAutoRouteEnabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfigService_IsAutoRouteEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAutoRouteEnabled'
type MockConfigService_IsAutoRouteEnabled_Call struct {
	*mock.Call
}

// IsAutoRouteEnabled is a helper method to define mock.On call
func (_e *MockConfigService_Expecter) IsAutoRouteEnabled() *MockConfigService_IsAutoRouteEnabled_Call {
	return &MockConfigService_IsAutoRouteEnabled_Call{Call: _e.mock.On("IsAutoRouteEnabled")}
}

func (_c *MockConfigService_IsAutoRouteEnabled_Call) Run(run func()) *MockConfigService_IsAutoRouteEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigService_IsAutoRouteEnabled_Call) Return(b bool) *MockConfigService_IsAutoRouteEnabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfigService_IsAutoRouteEnabled_Call) RunAndReturn(run func() bool) *MockConfigService_IsAutoRouteEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// IsNetworkIsolationEnabled provides a mock function for the type MockConfigService
func (_mock *MockConfigService) IsNetworkIsolationEnabled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsNetworkIsolationEnabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfigService_IsNetworkIsolationEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsNetworkIsolationEnabled'
type MockConfigService_IsNetworkIsolationEnabled_Call struct {
	*mock.Call
}

// IsNetworkIsolationEnabled is a helper method to define mock.On call
func (_e *MockConfigService_Expecter) IsNetworkIsolationEnabled() *MockConfigService_IsNetworkIsolationEnabled_Call {
	return &MockConfigService_IsNetworkIsolationEnabled_Call{Call: _e.mock.On("IsNetworkIsolationEnabled")}
}

func (_c *MockConfigService_IsNetworkIsolationEnabled_Call) Run(run func()) *MockConfigService_IsNetworkIsolationEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigService_IsNetworkIsolationEnabled_Call) Return(b bool) *MockConfigService_IsNetworkIsolationEnabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfigService_IsNetworkIsolationEnabled_Call) RunAndReturn(run func() bool) *MockConfigService_IsNetworkIsolationEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockConfigService
func (_mock *MockConfigService) Load(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigService_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockConfigService_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConfigService_Expecter) Load(ctx interface{}) *MockConfigService_Load_Call {
	return &MockConfigService_Load_Call{Call: _e.mock.On("Load", ctx)}
}

func (_c *MockConfigService_Load_Call) Run(run func(ctx context.Context)) *MockConfigService_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigService_Load_Call) Return(err error) *MockConfigService_Load_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigService_Load_Call) RunAndReturn(run func(ctx context.Context) error) *MockConfigService_Load_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveRoute provides a mock function for the type MockConfigService
func (_mock *MockConfigService) RemoveRoute(ctx context.Context, domain1 string) error {
	ret := _mock.Called(ctx, domain1)

	if len(ret) == 0 {
		panic("no return value specified for RemoveRoute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, domain1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigService_RemoveRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveRoute'
type MockConfigService_RemoveRoute_Call struct {
	*mock.Call
}

// RemoveRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - domain1 string
func (_e *MockConfigService_Expecter) RemoveRoute(ctx interface{}, domain1 interface{}) *MockConfigService_RemoveRoute_Call {
	return &MockConfigService_RemoveRoute_Call{Call: _e.mock.On("RemoveRoute", ctx, domain1)}
}

func (_c *MockConfigService_RemoveRoute_Call) Run(run func(ctx context.Context, domain1 string)) *MockConfigService_RemoveRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigService_RemoveRoute_Call) Return(err error) *MockConfigService_RemoveRoute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigService_RemoveRoute_Call) RunAndReturn(run func(ctx context.Context, domain1 string) error) *MockConfigService_RemoveRoute_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRoute provides a mock function for the type MockConfigService
func (_mock *MockConfigService) UpdateRoute(ctx context.Context, route domain.Route) error {
	ret := _mock.Called(ctx, route)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Route) error); ok {
		r0 = returnFunc(ctx, route)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigService_UpdateRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRoute'
type MockConfigService_UpdateRoute_Call struct {
	*mock.Call
}

// UpdateRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - route domain.Route
func (_e *MockConfigService_Expecter) UpdateRoute(ctx interface{}, route interface{}) *MockConfigService_UpdateRoute_Call {
	return &MockConfigService_UpdateRoute_Call{Call: _e.mock.On("UpdateRoute", ctx, route)}
}

func (_c *MockConfigService_UpdateRoute_Call) Run(run func(ctx context.Context, route domain.Route)) *MockConfigService_UpdateRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Route
		if args[1] != nil {
			arg1 = args[1].(domain.Route)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigService_UpdateRoute_Call) Return(err error) *MockConfigService_UpdateRoute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigService_UpdateRoute_Call) RunAndReturn(run func(ctx context.Context, route domain.Route) error) *MockConfigService_UpdateRoute_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function for the type MockConfigService
func (_mock *MockConfigService) Watch(ctx context.Context, onChange func()) error {
	ret := _mock.Called(ctx, onChange)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func()) error); ok {
		r0 = returnFunc(ctx, onChange)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigService_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type MockConfigService_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - onChange func()
func (_e *MockConfigService_Expecter) Watch(ctx interface{}, onChange interface{}) *MockConfigService_Watch_Call {
	return &MockConfigService_Watch_Call{Call: _e.mock.On("Watch", ctx, onChange)}
}

func (_c *MockConfigService_Watch_Call) Run(run func(ctx context.Context, onChange func())) *MockConfigService_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func()
		if args[1] != nil {
			arg1 = args[1].(func())
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigService_Watch_Call) Return(err error) *MockConfigService_Watch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigService_Watch_Call) RunAndReturn(run func(ctx context.Context, onChange func()) error) *MockConfigService_Watch_Call {
	_c.Call.Return(run)
	return _c
}
