// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/gordon/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockContainerService creates a new instance of MockContainerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContainerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContainerService {
	mock := &MockContainerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContainerService is an autogenerated mock type for the ContainerService type
type MockContainerService struct {
	mock.Mock
}

type MockContainerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContainerService) EXPECT() *MockContainerService_Expecter {
	return &MockContainerService_Expecter{mock: &_m.Mock}
}

// AutoStart provides a mock function for the type MockContainerService
func (_mock *MockContainerService) AutoStart(ctx context.Context, routes []domain.Route) error {
	ret := _mock.Called(ctx, routes)

	if len(ret) == 0 {
		panic("no return value specified for AutoStart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.Route) error); ok {
		r0 = returnFunc(ctx, routes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainerService_AutoStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoStart'
type MockContainerService_AutoStart_Call struct {
	*mock.Call
}

// AutoStart is a helper method to define mock.On call
//   - ctx context.Context
//   - routes []domain.Route
func (_e *MockContainerService_Expecter) AutoStart(ctx interface{}, routes interface{}) *MockContainerService_AutoStart_Call {
	return &MockContainerService_AutoStart_Call{Call: _e.mock.On("AutoStart", ctx, routes)}
}

func (_c *MockContainerService_AutoStart_Call) Run(run func(ctx context.Context, routes []domain.Route)) *MockContainerService_AutoStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.Route
		if args[1] != nil {
			arg1 = args[1].([]domain.Route)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContainerService_AutoStart_Call) Return(err error) *MockContainerService_AutoStart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainerService_AutoStart_Call) RunAndReturn(run func(ctx context.Context, routes []domain.Route) error) *MockContainerService_AutoStart_Call {
	_c.Call.Return(run)
	return _c
}

// Deploy provides a mock function for the type MockContainerService
func (_mock *MockContainerService) Deploy(ctx context.Context, route domain.Route) (*domain.Container, error) {
	ret := _mock.Called(ctx, route)

	if len(ret) == 0 {
		panic("no return value specified for Deploy")
	}

	var r0 *domain.Container
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Route) (*domain.Container, error)); ok {
		return returnFunc(ctx, route)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Route) *domain.Container); ok {
		r0 = returnFunc(ctx, route)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Container)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Route) error); ok {
		r1 = returnFunc(ctx, route)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainerService_Deploy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deploy'
type MockContainerService_Deploy_Call struct {
	*mock.Call
}

// Deploy is a helper method to define mock.On call
//   - ctx context.Context
//   - route domain.Route
func (_e *MockContainerService_Expecter) Deploy(ctx interface{}, route interface{}) *MockContainerService_Deploy_Call {
	return &MockContainerService_Deploy_Call{Call: _e.mock.On("Deploy", ctx, route)}
}

func (_c *MockContainerService_Deploy_Call) Run(run func(ctx context.Context, route domain.Route)) *MockContainerService_Deploy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Route
		if args[1] != nil {
			arg1 = args[1].(domain.Route)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContainerService_Deploy_Call) Return(container *domain.Container, err error) *MockContainerService_Deploy_Call {
	_c.Call.Return(container, err)
	return _c
}

func (_c *MockContainerService_Deploy_Call) RunAndReturn(run func(ctx context.Context, route domain.Route) (*domain.Container, error)) *MockContainerService_Deploy_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockContainerService
func (_mock *MockContainerService) Get(ctx context.Context, domain1 string) (*domain.Container, bool) {
	ret := _mock.Called(ctx, domain1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Container
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Container, bool)); ok {
		return returnFunc(ctx, domain1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Container); ok {
		r0 = returnFunc(ctx, domain1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Container)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, domain1)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockContainerService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockContainerService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - domain1 string
func (_e *MockContainerService_Expecter) Get(ctx interface{}, domain1 interface{}) *MockContainerService_Get_Call {
	return &MockContainerService_Get_Call{Call: _e.mock.On("Get", ctx, domain1)}
}

func (_c *MockContainerService_Get_Call) Run(run func(ctx context.Context, domain1 string)) *MockContainerService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContainerService_Get_Call) Return(container *domain.Container, b bool) *MockContainerService_Get_Call {
	_c.Call.Return(container, b)
	return _c
}

func (_c *MockContainerService_Get_Call) RunAndReturn(run func(ctx context.Context, domain1 string) (*domain.Container, bool)) *MockContainerService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// HealthCheck provides a mock function for the type MockContainerService
func (_mock *MockContainerService) HealthCheck(ctx context.Context) map[string]bool {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 map[string]bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]bool); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]bool)
		}
	}
	return r0
}

// MockContainerService_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockContainerService_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockContainerService_Expecter) HealthCheck(ctx interface{}) *MockContainerService_HealthCheck_Call {
	return &MockContainerService_HealthCheck_Call{Call: _e.mock.On("HealthCheck", ctx)}
}

func (_c *MockContainerService_HealthCheck_Call) Run(run func(ctx context.Context)) *MockContainerService_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainerService_HealthCheck_Call) Return(stringToBool map[string]bool) *MockContainerService_HealthCheck_Call {
	_c.Call.Return(stringToBool)
	return _c
}

func (_c *MockContainerService_HealthCheck_Call) RunAndReturn(run func(ctx context.Context) map[string]bool) *MockContainerService_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockContainerService
func (_mock *MockContainerService) List(ctx context.Context) map[string]*domain.Container {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 map[string]*domain.Container
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]*domain.Container); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*domain.Container)
		}
	}
	return r0
}

// MockContainerService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockContainerService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockContainerService_Expecter) List(ctx interface{}) *MockContainerService_List_Call {
	return &MockContainerService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockContainerService_List_Call) Run(run func(ctx context.Context)) *MockContainerService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainerService_List_Call) Return(stringToContainer map[string]*domain.Container) *MockContainerService_List_Call {
	_c.Call.Return(stringToContainer)
	return _c
}

func (_c *MockContainerService_List_Call) RunAndReturn(run func(ctx context.Context) map[string]*domain.Container) *MockContainerService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListAttachments provides a mock function for the type MockContainerService
func (_mock *MockContainerService) ListAttachments(ctx context.Context, domain1 string) []domain.Attachment {
	ret := _mock.Called(ctx, domain1)

	if len(ret) == 0 {
		panic("no return value specified for ListAttachments")
	}

	var r0 []domain.Attachment
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.Attachment); ok {
		r0 = returnFunc(ctx, domain1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Attachment)
		}
	}
	return r0
}

// MockContainerService_ListAttachments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAttachments'
type MockContainerService_ListAttachments_Call struct {
	*mock.Call
}

// ListAttachments is a helper method to define mock.On call
//   - ctx context.Context
//   - domain1 string
func (_e *MockContainerService_Expecter) ListAttachments(ctx interface{}, domain1 interface{}) *MockContainerService_ListAttachments_Call {
	return &MockContainerService_ListAttachments_Call{Call: _e.mock.On("ListAttachments", ctx, domain1)}
}

func (_c *MockContainerService_ListAttachments_Call) Run(run func(ctx context.Context, domain1 string)) *MockContainerService_ListAttachments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContainerService_ListAttachments_Call) Return(attachments []domain.Attachment) *MockContainerService_ListAttachments_Call {
	_c.Call.Return(attachments)
	return _c
}

func (_c *MockContainerService_ListAttachments_Call) RunAndReturn(run func(ctx context.Context, domain1 string) []domain.Attachment) *MockContainerService_ListAttachments_Call {
	_c.Call.Return(run)
	return _c
}

// ListNetworks provides a mock function for the type MockContainerService
func (_mock *MockContainerService) ListNetworks(ctx context.Context) ([]*domain.NetworkInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListNetworks")
	}

	var r0 []*domain.NetworkInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.NetworkInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.NetworkInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.NetworkInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainerService_ListNetworks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNetworks'
type MockContainerService_ListNetworks_Call struct {
	*mock.Call
}

// ListNetworks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockContainerService_Expecter) ListNetworks(ctx interface{}) *MockContainerService_ListNetworks_Call {
	return &MockContainerService_ListNetworks_Call{Call: _e.mock.On("ListNetworks", ctx)}
}

func (_c *MockContainerService_ListNetworks_Call) Run(run func(ctx context.Context)) *MockContainerService_ListNetworks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainerService_ListNetworks_Call) Return(networkInfos []*domain.NetworkInfo, err error) *MockContainerService_ListNetworks_Call {
	_c.Call.Return(networkInfos, err)
	return _c
}

func (_c *MockContainerService_ListNetworks_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.NetworkInfo, error)) *MockContainerService_ListNetworks_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoutesWithDetails provides a mock function for the type MockContainerService
func (_mock *MockContainerService) ListRoutesWithDetails(ctx context.Context) []domain.RouteInfo {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRoutesWithDetails")
	}

	var r0 []domain.RouteInfo
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.RouteInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.RouteInfo)
		}
	}
	return r0
}

// MockContainerService_ListRoutesWithDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoutesWithDetails'
type MockContainerService_ListRoutesWithDetails_Call struct {
	*mock.Call
}

// ListRoutesWithDetails is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockContainerService_Expecter) ListRoutesWithDetails(ctx interface{}) *MockContainerService_ListRoutesWithDetails_Call {
	return &MockContainerService_ListRoutesWithDetails_Call{Call: _e.mock.On("ListRoutesWithDetails", ctx)}
}

func (_c *MockContainerService_ListRoutesWithDetails_Call) Run(run func(ctx context.Context)) *MockContainerService_ListRoutesWithDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainerService_ListRoutesWithDetails_Call) Return(routeInfos []domain.RouteInfo) *MockContainerService_ListRoutesWithDetails_Call {
	_c.Call.Return(routeInfos)
	return _c
}

func (_c *MockContainerService_ListRoutesWithDetails_Call) RunAndReturn(run func(ctx context.Context) []domain.RouteInfo) *MockContainerService_ListRoutesWithDetails_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockContainerService
func (_mock *MockContainerService) Remove(ctx context.Context, containerID string, force bool) error {
	ret := _mock.Called(ctx, containerID, force)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, containerID, force)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainerService_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockContainerService_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - force bool
func (_e *MockContainerService_Expecter) Remove(ctx interface{}, containerID interface{}, force interface{}) *MockContainerService_Remove_Call {
	return &MockContainerService_Remove_Call{Call: _e.mock.On("Remove", ctx, containerID, force)}
}

func (_c *MockContainerService_Remove_Call) Run(run func(ctx context.Context, containerID string, force bool)) *MockContainerService_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockContainerService_Remove_Call) Return(err error) *MockContainerService_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainerService_Remove_Call) RunAndReturn(run func(ctx context.Context, containerID string, force bool) error) *MockContainerService_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Restart provides a mock function for the type MockContainerService
func (_mock *MockContainerService) Restart(ctx context.Context, domain1 string, withAttachments bool) error {
	ret := _mock.Called(ctx, domain1, withAttachments)

	if len(ret) == 0 {
		panic("no return value specified for Restart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, domain1, withAttachments)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainerService_Restart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restart'
type MockContainerService_Restart_Call struct {
	*mock.Call
}

// Restart is a helper method to define mock.On call
//   - ctx context.Context
//   - domain1 string
//   - withAttachments bool
func (_e *MockContainerService_Expecter) Restart(ctx interface{}, domain1 interface{}, withAttachments interface{}) *MockContainerService_Restart_Call {
	return &MockContainerService_Restart_Call{Call: _e.mock.On("Restart", ctx, domain1, withAttachments)}
}

func (_c *MockContainerService_Restart_Call) Run(run func(ctx context.Context, domain1 string, withAttachments bool)) *MockContainerService_Restart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockContainerService_Restart_Call) Return(err error) *MockContainerService_Restart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainerService_Restart_Call) RunAndReturn(run func(ctx context.Context, domain1 string, withAttachments bool) error) *MockContainerService_Restart_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockContainerService
func (_mock *MockContainerService) Shutdown(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainerService_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockContainerService_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockContainerService_Expecter) Shutdown(ctx interface{}) *MockContainerService_Shutdown_Call {
	return &MockContainerService_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockContainerService_Shutdown_Call) Run(run func(ctx context.Context)) *MockContainerService_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainerService_Shutdown_Call) Return(err error) *MockContainerService_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainerService_Shutdown_Call) RunAndReturn(run func(ctx context.Context) error) *MockContainerService_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockContainerService
func (_mock *MockContainerService) Stop(ctx context.Context, containerID string) error {
	ret := _mock.Called(ctx, containerID)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, containerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainerService_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockContainerService_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
func (_e *MockContainerService_Expecter) Stop(ctx interface{}, containerID interface{}) *MockContainerService_Stop_Call {
	return &MockContainerService_Stop_Call{Call: _e.mock.On("Stop", ctx, containerID)}
}

func (_c *MockContainerService_Stop_Call) Run(run func(ctx context.Context, containerID string)) *MockContainerService_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContainerService_Stop_Call) Return(err error) *MockContainerService_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainerService_Stop_Call) RunAndReturn(run func(ctx context.Context, containerID string) error) *MockContainerService_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// SyncContainers provides a mock function for the type MockContainerService
func (_mock *MockContainerService) SyncContainers(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SyncContainers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainerService_SyncContainers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncContainers'
type MockContainerService_SyncContainers_Call struct {
	*mock.Call
}

// SyncContainers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockContainerService_Expecter) SyncContainers(ctx interface{}) *MockContainerService_SyncContainers_Call {
	return &MockContainerService_SyncContainers_Call{Call: _e.mock.On("SyncContainers", ctx)}
}

func (_c *MockContainerService_SyncContainers_Call) Run(run func(ctx context.Context)) *MockContainerService_SyncContainers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainerService_SyncContainers_Call) Return(err error) *MockContainerService_SyncContainers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainerService_SyncContainers_Call) RunAndReturn(run func(ctx context.Context) error) *MockContainerService_SyncContainers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAttachments provides a mock function for the type MockContainerService
func (_mock *MockContainerService) UpdateAttachments(attachments map[string][]string) {
	_mock.Called(attachments)
}

// MockContainerService_UpdateAttachments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAttachments'
type MockContainerService_UpdateAttachments_Call struct {
	*mock.Call
}

// UpdateAttachments is a helper method to define mock.On call
//   - attachments map[string][]string
func (_e *MockContainerService_Expecter) UpdateAttachments(attachments interface{}) *MockContainerService_UpdateAttachments_Call {
	return &MockContainerService_UpdateAttachments_Call{Call: _e.mock.On("UpdateAttachments", attachments)}
}

func (_c *MockContainerService_UpdateAttachments_Call) Run(run func(attachments map[string][]string)) *MockContainerService_UpdateAttachments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string][]string
		if args[0] != nil {
			arg0 = args[0].(map[string][]string)
		}
		run(arg0)
	})
	return _c
}

func (_c *MockContainerService_UpdateAttachments_Call) Return() *MockContainerService_UpdateAttachments_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockContainerService_UpdateAttachments_Call) RunAndReturn(run func(attachments map[string][]string)) *MockContainerService_UpdateAttachments_Call {
	_c.Call.Return(run)
	return _c
}
