// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAppReconciler creates a new instance of MockAppReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAppReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAppReconciler {
	mock := &MockAppReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAppReconciler is an autogenerated mock type for the AppReconciler type
type MockAppReconciler struct {
	mock.Mock
}

type MockAppReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAppReconciler) EXPECT() *MockAppReconciler_Expecter {
	return &MockAppReconciler_Expecter{mock: &_m.Mock}
}

// ReconcileRunning provides a mock function for the type MockAppReconciler
func (_mock *MockAppReconciler) ReconcileRunning(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReconcileRunning")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAppReconciler_ReconcileRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconcileRunning'
type MockAppReconciler_ReconcileRunning_Call struct {
	*mock.Call
}

// ReconcileRunning is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAppReconciler_Expecter) ReconcileRunning(ctx any) *MockAppReconciler_ReconcileRunning_Call {
	return &MockAppReconciler_ReconcileRunning_Call{Call: _e.mock.On("ReconcileRunning", ctx)}
}

func (_c *MockAppReconciler_ReconcileRunning_Call) Run(run func(ctx context.Context)) *MockAppReconciler_ReconcileRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAppReconciler_ReconcileRunning_Call) Return(err error) *MockAppReconciler_ReconcileRunning_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAppReconciler_ReconcileRunning_Call) RunAndReturn(run func(ctx context.Context) error) *MockAppReconciler_ReconcileRunning_Call {
	_c.Call.Return(run)
	return _c
}
