// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gordon/edge/v1/edge.proto

package edgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DrainTimeoutReason is a closed, sanitised timeout vocabulary. It must never
// contain raw runtime or network error material.
type DrainTimeoutReason int32

const (
	DrainTimeoutReason_DRAIN_TIMEOUT_REASON_UNSPECIFIED DrainTimeoutReason = 0
	DrainTimeoutReason_DRAIN_TIMEOUT_REASON_EDGE        DrainTimeoutReason = 1
	DrainTimeoutReason_DRAIN_TIMEOUT_REASON_CONTROL     DrainTimeoutReason = 2
)

// Enum value maps for DrainTimeoutReason.
var (
	DrainTimeoutReason_name = map[int32]string{
		0: "DRAIN_TIMEOUT_REASON_UNSPECIFIED",
		1: "DRAIN_TIMEOUT_REASON_EDGE",
		2: "DRAIN_TIMEOUT_REASON_CONTROL",
	}
	DrainTimeoutReason_value = map[string]int32{
		"DRAIN_TIMEOUT_REASON_UNSPECIFIED": 0,
		"DRAIN_TIMEOUT_REASON_EDGE":        1,
		"DRAIN_TIMEOUT_REASON_CONTROL":     2,
	}
)

func (x DrainTimeoutReason) Enum() *DrainTimeoutReason {
	p := new(DrainTimeoutReason)
	*p = x
	return p
}

func (x DrainTimeoutReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DrainTimeoutReason) Descriptor() protoreflect.EnumDescriptor {
	return file_gordon_edge_v1_edge_proto_enumTypes[0].Descriptor()
}

func (DrainTimeoutReason) Type() protoreflect.EnumType {
	return &file_gordon_edge_v1_edge_proto_enumTypes[0]
}

func (x DrainTimeoutReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DrainTimeoutReason.Descriptor instead.
func (DrainTimeoutReason) EnumDescriptor() ([]byte, []int) {
	return file_gordon_edge_v1_edge_proto_rawDescGZIP(), []int{0}
}

// WatchRouteSnapshotsRequest deliberately has no routing selectors.
type WatchRouteSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRouteSnapshotsRequest) Reset() {
	*x = WatchRouteSnapshotsRequest{}
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRouteSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRouteSnapshotsRequest) ProtoMessage() {}

func (x *WatchRouteSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRouteSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*WatchRouteSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_gordon_edge_v1_edge_proto_rawDescGZIP(), []int{0}
}

// WatchTrafficGraphsRequest deliberately has no selectors: the authenticated
// edge receives exactly its control-owned sanitized graph.
type WatchTrafficGraphsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTrafficGraphsRequest) Reset() {
	*x = WatchTrafficGraphsRequest{}
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTrafficGraphsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTrafficGraphsRequest) ProtoMessage() {}

func (x *WatchTrafficGraphsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTrafficGraphsRequest.ProtoReflect.Descriptor instead.
func (*WatchTrafficGraphsRequest) Descriptor() ([]byte, []int) {
	return file_gordon_edge_v1_edge_proto_rawDescGZIP(), []int{1}
}

// TrafficGraphSnapshot carries traffic options, entry points, routers, and
// backends only. Certificates, keys, ACME state, and control configuration are
// intentionally absent.
type TrafficGraphSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Options       *TrafficOptions        `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	EntryPoints   []*TrafficEntryPoint   `protobuf:"bytes,3,rep,name=entry_points,json=entryPoints,proto3" json:"entry_points,omitempty"`
	Routers       []*TrafficRouter       `protobuf:"bytes,4,rep,name=routers,proto3" json:"routers,omitempty"`
	Services      []*TrafficService      `protobuf:"bytes,5,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficGraphSnapshot) Reset() {
	*x = TrafficGraphSnapshot{}
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficGraphSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficGraphSnapshot) ProtoMessage() {}

func (x *TrafficGraphSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficGraphSnapshot.ProtoReflect.Descriptor instead.
func (*TrafficGraphSnapshot) Descriptor() ([]byte, []int) {
	return file_gordon_edge_v1_edge_proto_rawDescGZIP(), []int{2}
}

func (x *TrafficGraphSnapshot) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *TrafficGraphSnapshot) GetOptions() *TrafficOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *TrafficGraphSnapshot) GetEntryPoints() []*TrafficEntryPoint {
	if x != nil {
		return x.EntryPoints
	}
	return nil
}

func (x *TrafficGraphSnapshot) GetRouters() []*TrafficRouter {
	if x != nil {
		return x.Routers
	}
	return nil
}

func (x *TrafficGraphSnapshot) GetServices() []*TrafficService {
	if x != nil {
		return x.Services
	}
	return nil
}

type TrafficOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tcp           *TrafficTCPOptions     `protobuf:"bytes,1,opt,name=tcp,proto3" json:"tcp,omitempty"`
	Udp           *TrafficUDPOptions     `protobuf:"bytes,2,opt,name=udp,proto3" json:"udp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficOptions) Reset() {
	*x = TrafficOptions{}
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficOptions) ProtoMessage() {}

func (x *TrafficOptions) ProtoReflect() protoreflect.Message {
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficOptions.ProtoReflect.Descriptor instead.
func (*TrafficOptions) Descriptor() ([]byte, []int) {
	return file_gordon_edge_v1_edge_proto_rawDescGZIP(), []int{3}
}

func (x *TrafficOptions) GetTcp() *TrafficTCPOptions {
	if x != nil {
		return x.Tcp
	}
	return nil
}

func (x *TrafficOptions) GetUdp() *TrafficUDPOptions {
	if x != nil {
		return x.Udp
	}
	return nil
}

type TrafficTCPOptions struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DialTimeoutNanos  int64                  `protobuf:"varint,1,opt,name=dial_timeout_nanos,json=dialTimeoutNanos,proto3" json:"dial_timeout_nanos,omitempty"`
	IdleTimeoutNanos  int64                  `protobuf:"varint,2,opt,name=idle_timeout_nanos,json=idleTimeoutNanos,proto3" json:"idle_timeout_nanos,omitempty"`
	DrainTimeoutNanos int64                  `protobuf:"varint,3,opt,name=drain_timeout_nanos,json=drainTimeoutNanos,proto3" json:"drain_timeout_nanos,omitempty"`
	MaxConnections    int64                  `protobuf:"varint,4,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TrafficTCPOptions) Reset() {
	*x = TrafficTCPOptions{}
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficTCPOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficTCPOptions) ProtoMessage() {}

func (x *TrafficTCPOptions) ProtoReflect() protoreflect.Message {
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficTCPOptions.ProtoReflect.Descriptor instead.
func (*TrafficTCPOptions) Descriptor() ([]byte, []int) {
	return file_gordon_edge_v1_edge_proto_rawDescGZIP(), []int{4}
}

func (x *TrafficTCPOptions) GetDialTimeoutNanos() int64 {
	if x != nil {
		return x.DialTimeoutNanos
	}
	return 0
}

func (x *TrafficTCPOptions) GetIdleTimeoutNanos() int64 {
	if x != nil {
		return x.IdleTimeoutNanos
	}
	return 0
}

func (x *TrafficTCPOptions) GetDrainTimeoutNanos() int64 {
	if x != nil {
		return x.DrainTimeoutNanos
	}
	return 0
}

func (x *TrafficTCPOptions) GetMaxConnections() int64 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

type TrafficUDPOptions struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IdleTimeoutNanos  int64                  `protobuf:"varint,1,opt,name=idle_timeout_nanos,json=idleTimeoutNanos,proto3" json:"idle_timeout_nanos,omitempty"`
	DrainTimeoutNanos int64                  `protobuf:"varint,2,opt,name=drain_timeout_nanos,json=drainTimeoutNanos,proto3" json:"drain_timeout_nanos,omitempty"`
	MaxSessions       int64                  `protobuf:"varint,3,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TrafficUDPOptions) Reset() {
	*x = TrafficUDPOptions{}
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficUDPOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficUDPOptions) ProtoMessage() {}

func (x *TrafficUDPOptions) ProtoReflect() protoreflect.Message {
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficUDPOptions.ProtoReflect.Descriptor instead.
func (*TrafficUDPOptions) Descriptor() ([]byte, []int) {
	return file_gordon_edge_v1_edge_proto_rawDescGZIP(), []int{5}
}

func (x *TrafficUDPOptions) GetIdleTimeoutNanos() int64 {
	if x != nil {
		return x.IdleTimeoutNanos
	}
	return 0
}

func (x *TrafficUDPOptions) GetDrainTimeoutNanos() int64 {
	if x != nil {
		return x.DrainTimeoutNanos
	}
	return 0
}

func (x *TrafficUDPOptions) GetMaxSessions() int64 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

type TrafficEntryPoint struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Name                    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address                 string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Protocol                string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	TrustedCidrs            []string               `protobuf:"bytes,4,rep,name=trusted_cidrs,json=trustedCidrs,proto3" json:"trusted_cidrs,omitempty"`
	RawFallback             string                 `protobuf:"bytes,5,opt,name=raw_fallback,json=rawFallback,proto3" json:"raw_fallback,omitempty"`
	RawFallbackTrustedCidrs []string               `protobuf:"bytes,6,rep,name=raw_fallback_trusted_cidrs,json=rawFallbackTrustedCidrs,proto3" json:"raw_fallback_trusted_cidrs,omitempty"`
	AllowPublicRawFallback  bool                   `protobuf:"varint,7,opt,name=allow_public_raw_fallback,json=allowPublicRawFallback,proto3" json:"allow_public_raw_fallback,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TrafficEntryPoint) Reset() {
	*x = TrafficEntryPoint{}
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficEntryPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficEntryPoint) ProtoMessage() {}

func (x *TrafficEntryPoint) ProtoReflect() protoreflect.Message {
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficEntryPoint.ProtoReflect.Descriptor instead.
func (*TrafficEntryPoint) Descriptor() ([]byte, []int) {
	return file_gordon_edge_v1_edge_proto_rawDescGZIP(), []int{6}
}

func (x *TrafficEntryPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrafficEntryPoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TrafficEntryPoint) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *TrafficEntryPoint) GetTrustedCidrs() []string {
	if x != nil {
		return x.TrustedCidrs
	}
	return nil
}

func (x *TrafficEntryPoint) GetRawFallback() string {
	if x != nil {
		return x.RawFallback
	}
	return ""
}

func (x *TrafficEntryPoint) GetRawFallbackTrustedCidrs() []string {
	if x != nil {
		return x.RawFallbackTrustedCidrs
	}
	return nil
}

func (x *TrafficEntryPoint) GetAllowPublicRawFallback() bool {
	if x != nil {
		return x.AllowPublicRawFallback
	}
	return false
}

type TrafficRouter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EntryPoint    string                 `protobuf:"bytes,2,opt,name=entry_point,json=entryPoint,proto3" json:"entry_point,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Rule          *TrafficRule           `protobuf:"bytes,4,opt,name=rule,proto3" json:"rule,omitempty"`
	Service       string                 `protobuf:"bytes,5,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficRouter) Reset() {
	*x = TrafficRouter{}
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficRouter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficRouter) ProtoMessage() {}

func (x *TrafficRouter) ProtoReflect() protoreflect.Message {
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficRouter.ProtoReflect.Descriptor instead.
func (*TrafficRouter) Descriptor() ([]byte, []int) {
	return file_gordon_edge_v1_edge_proto_rawDescGZIP(), []int{7}
}

func (x *TrafficRouter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrafficRouter) GetEntryPoint() string {
	if x != nil {
		return x.EntryPoint
	}
	return ""
}

func (x *TrafficRouter) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *TrafficRouter) GetRule() *TrafficRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *TrafficRouter) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type TrafficRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Sni           string                 `protobuf:"bytes,2,opt,name=sni,proto3" json:"sni,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficRule) Reset() {
	*x = TrafficRule{}
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficRule) ProtoMessage() {}

func (x *TrafficRule) ProtoReflect() protoreflect.Message {
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficRule.ProtoReflect.Descriptor instead.
func (*TrafficRule) Descriptor() ([]byte, []int) {
	return file_gordon_edge_v1_edge_proto_rawDescGZIP(), []int{8}
}

func (x *TrafficRule) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TrafficRule) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

type TrafficService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Backends      []*TrafficBackend      `protobuf:"bytes,2,rep,name=backends,proto3" json:"backends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficService) Reset() {
	*x = TrafficService{}
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficService) ProtoMessage() {}

func (x *TrafficService) ProtoReflect() protoreflect.Message {
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficService.ProtoReflect.Descriptor instead.
func (*TrafficService) Descriptor() ([]byte, []int) {
	return file_gordon_edge_v1_edge_proto_rawDescGZIP(), []int{9}
}

func (x *TrafficService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrafficService) GetBackends() []*TrafficBackend {
	if x != nil {
		return x.Backends
	}
	return nil
}

type TrafficBackend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficBackend) Reset() {
	*x = TrafficBackend{}
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficBackend) ProtoMessage() {}

func (x *TrafficBackend) ProtoReflect() protoreflect.Message {
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficBackend.ProtoReflect.Descriptor instead.
func (*TrafficBackend) Descriptor() ([]byte, []int) {
	return file_gordon_edge_v1_edge_proto_rawDescGZIP(), []int{10}
}

func (x *TrafficBackend) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrafficBackend) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TrafficBackend) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *TrafficBackend) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

// RouteTargetSnapshot is the complete sanitized routing view for an edge.
type RouteTargetSnapshot struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Generation               uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Entries                  []*RouteTargetEntry    `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	RegistryForwardingTarget *RouteTargetEntry      `protobuf:"bytes,3,opt,name=registry_forwarding_target,json=registryForwardingTarget,proto3" json:"registry_forwarding_target,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RouteTargetSnapshot) Reset() {
	*x = RouteTargetSnapshot{}
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteTargetSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTargetSnapshot) ProtoMessage() {}

func (x *RouteTargetSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTargetSnapshot.ProtoReflect.Descriptor instead.
func (*RouteTargetSnapshot) Descriptor() ([]byte, []int) {
	return file_gordon_edge_v1_edge_proto_rawDescGZIP(), []int{11}
}

func (x *RouteTargetSnapshot) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *RouteTargetSnapshot) GetEntries() []*RouteTargetEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *RouteTargetSnapshot) GetRegistryForwardingTarget() *RouteTargetEntry {
	if x != nil {
		return x.RegistryForwardingTarget
	}
	return nil
}

// RouteTargetEntry contains only the data needed to proxy one route target.
type RouteTargetEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CanonicalDomain   string                 `protobuf:"bytes,1,opt,name=canonical_domain,json=canonicalDomain,proto3" json:"canonical_domain,omitempty"`
	TargetHost        string                 `protobuf:"bytes,2,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	TargetPort        int32                  `protobuf:"varint,3,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	Scheme            string                 `protobuf:"bytes,4,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Protocol          string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Status            string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	UnavailableReason string                 `protobuf:"bytes,7,opt,name=unavailable_reason,json=unavailableReason,proto3" json:"unavailable_reason,omitempty"`
	Generation        uint64                 `protobuf:"varint,8,opt,name=generation,proto3" json:"generation,omitempty"`
	UpstreamHost      string                 `protobuf:"bytes,9,opt,name=upstream_host,json=upstreamHost,proto3" json:"upstream_host,omitempty"`
	Attachment        string                 `protobuf:"bytes,10,opt,name=attachment,proto3" json:"attachment,omitempty"`
	TargetKey         string                 `protobuf:"bytes,11,opt,name=target_key,json=targetKey,proto3" json:"target_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RouteTargetEntry) Reset() {
	*x = RouteTargetEntry{}
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteTargetEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTargetEntry) ProtoMessage() {}

func (x *RouteTargetEntry) ProtoReflect() protoreflect.Message {
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTargetEntry.ProtoReflect.Descriptor instead.
func (*RouteTargetEntry) Descriptor() ([]byte, []int) {
	return file_gordon_edge_v1_edge_proto_rawDescGZIP(), []int{12}
}

func (x *RouteTargetEntry) GetCanonicalDomain() string {
	if x != nil {
		return x.CanonicalDomain
	}
	return ""
}

func (x *RouteTargetEntry) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *RouteTargetEntry) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *RouteTargetEntry) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *RouteTargetEntry) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *RouteTargetEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RouteTargetEntry) GetUnavailableReason() string {
	if x != nil {
		return x.UnavailableReason
	}
	return ""
}

func (x *RouteTargetEntry) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *RouteTargetEntry) GetUpstreamHost() string {
	if x != nil {
		return x.UpstreamHost
	}
	return ""
}

func (x *RouteTargetEntry) GetAttachment() string {
	if x != nil {
		return x.Attachment
	}
	return ""
}

func (x *RouteTargetEntry) GetTargetKey() string {
	if x != nil {
		return x.TargetKey
	}
	return ""
}

// ReportDrainStateRequest carries no edge identity; authentication provides it.
// target_key is opaque and must not be a target alias or backing/container ID.
type ReportDrainStateRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CanonicalDomain      string                 `protobuf:"bytes,1,opt,name=canonical_domain,json=canonicalDomain,proto3" json:"canonical_domain,omitempty"`
	TransitionGeneration uint64                 `protobuf:"varint,2,opt,name=transition_generation,json=transitionGeneration,proto3" json:"transition_generation,omitempty"`
	OldTargetKey         string                 `protobuf:"bytes,3,opt,name=old_target_key,json=oldTargetKey,proto3" json:"old_target_key,omitempty"`
	InFlight             uint64                 `protobuf:"varint,4,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`
	// Informational edge time only; control records the trusted receipt time.
	AcknowledgedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=acknowledged_at,json=acknowledgedAt,proto3" json:"acknowledged_at,omitempty"`
	TimeoutReason  DrainTimeoutReason     `protobuf:"varint,6,opt,name=timeout_reason,json=timeoutReason,proto3,enum=gordon.edge.v1.DrainTimeoutReason" json:"timeout_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportDrainStateRequest) Reset() {
	*x = ReportDrainStateRequest{}
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDrainStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDrainStateRequest) ProtoMessage() {}

func (x *ReportDrainStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDrainStateRequest.ProtoReflect.Descriptor instead.
func (*ReportDrainStateRequest) Descriptor() ([]byte, []int) {
	return file_gordon_edge_v1_edge_proto_rawDescGZIP(), []int{13}
}

func (x *ReportDrainStateRequest) GetCanonicalDomain() string {
	if x != nil {
		return x.CanonicalDomain
	}
	return ""
}

func (x *ReportDrainStateRequest) GetTransitionGeneration() uint64 {
	if x != nil {
		return x.TransitionGeneration
	}
	return 0
}

func (x *ReportDrainStateRequest) GetOldTargetKey() string {
	if x != nil {
		return x.OldTargetKey
	}
	return ""
}

func (x *ReportDrainStateRequest) GetInFlight() uint64 {
	if x != nil {
		return x.InFlight
	}
	return 0
}

func (x *ReportDrainStateRequest) GetAcknowledgedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AcknowledgedAt
	}
	return nil
}

func (x *ReportDrainStateRequest) GetTimeoutReason() DrainTimeoutReason {
	if x != nil {
		return x.TimeoutReason
	}
	return DrainTimeoutReason_DRAIN_TIMEOUT_REASON_UNSPECIFIED
}

// ReportDrainStateResponse intentionally has no drain orchestration semantics.
type ReportDrainStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDrainStateResponse) Reset() {
	*x = ReportDrainStateResponse{}
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDrainStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDrainStateResponse) ProtoMessage() {}

func (x *ReportDrainStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDrainStateResponse.ProtoReflect.Descriptor instead.
func (*ReportDrainStateResponse) Descriptor() ([]byte, []int) {
	return file_gordon_edge_v1_edge_proto_rawDescGZIP(), []int{14}
}

// ReportAppliedStateRequest is deliberately small. component_id must equal the
// authenticated edge identity; it is not an authority chosen by the caller.
type ReportAppliedStateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ComponentId       string                 `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	RouteGeneration   uint64                 `protobuf:"varint,2,opt,name=route_generation,json=routeGeneration,proto3" json:"route_generation,omitempty"`
	TrafficGeneration uint64                 `protobuf:"varint,3,opt,name=traffic_generation,json=trafficGeneration,proto3" json:"traffic_generation,omitempty"`
	Healthy           bool                   `protobuf:"varint,4,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReportAppliedStateRequest) Reset() {
	*x = ReportAppliedStateRequest{}
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAppliedStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAppliedStateRequest) ProtoMessage() {}

func (x *ReportAppliedStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAppliedStateRequest.ProtoReflect.Descriptor instead.
func (*ReportAppliedStateRequest) Descriptor() ([]byte, []int) {
	return file_gordon_edge_v1_edge_proto_rawDescGZIP(), []int{15}
}

func (x *ReportAppliedStateRequest) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *ReportAppliedStateRequest) GetRouteGeneration() uint64 {
	if x != nil {
		return x.RouteGeneration
	}
	return 0
}

func (x *ReportAppliedStateRequest) GetTrafficGeneration() uint64 {
	if x != nil {
		return x.TrafficGeneration
	}
	return 0
}

func (x *ReportAppliedStateRequest) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type ReportAppliedStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAppliedStateResponse) Reset() {
	*x = ReportAppliedStateResponse{}
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAppliedStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAppliedStateResponse) ProtoMessage() {}

func (x *ReportAppliedStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gordon_edge_v1_edge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAppliedStateResponse.ProtoReflect.Descriptor instead.
func (*ReportAppliedStateResponse) Descriptor() ([]byte, []int) {
	return file_gordon_edge_v1_edge_proto_rawDescGZIP(), []int{16}
}

var File_gordon_edge_v1_edge_proto protoreflect.FileDescriptor

const file_gordon_edge_v1_edge_proto_rawDesc = "" +
	"\n" +
	"\x19gordon/edge/v1/edge.proto\x12\x0egordon.edge.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1c\n" +
	"\x1aWatchRouteSnapshotsRequest\"\x1b\n" +
	"\x19WatchTrafficGraphsRequest\"\xab\x02\n" +
	"\x14TrafficGraphSnapshot\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x128\n" +
	"\aoptions\x18\x02 \x01(\v2\x1e.gordon.edge.v1.TrafficOptionsR\aoptions\x12D\n" +
	"\fentry_points\x18\x03 \x03(\v2!.gordon.edge.v1.TrafficEntryPointR\ventryPoints\x127\n" +
	"\arouters\x18\x04 \x03(\v2\x1d.gordon.edge.v1.TrafficRouterR\arouters\x12:\n" +
	"\bservices\x18\x05 \x03(\v2\x1e.gordon.edge.v1.TrafficServiceR\bservices\"z\n" +
	"\x0eTrafficOptions\x123\n" +
	"\x03tcp\x18\x01 \x01(\v2!.gordon.edge.v1.TrafficTCPOptionsR\x03tcp\x123\n" +
	"\x03udp\x18\x02 \x01(\v2!.gordon.edge.v1.TrafficUDPOptionsR\x03udp\"\xc8\x01\n" +
	"\x11TrafficTCPOptions\x12,\n" +
	"\x12dial_timeout_nanos\x18\x01 \x01(\x03R\x10dialTimeoutNanos\x12,\n" +
	"\x12idle_timeout_nanos\x18\x02 \x01(\x03R\x10idleTimeoutNanos\x12.\n" +
	"\x13drain_timeout_nanos\x18\x03 \x01(\x03R\x11drainTimeoutNanos\x12'\n" +
	"\x0fmax_connections\x18\x04 \x01(\x03R\x0emaxConnections\"\x94\x01\n" +
	"\x11TrafficUDPOptions\x12,\n" +
	"\x12idle_timeout_nanos\x18\x01 \x01(\x03R\x10idleTimeoutNanos\x12.\n" +
	"\x13drain_timeout_nanos\x18\x02 \x01(\x03R\x11drainTimeoutNanos\x12!\n" +
	"\fmax_sessions\x18\x03 \x01(\x03R\vmaxSessions\"\x9d\x02\n" +
	"\x11TrafficEntryPoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12#\n" +
	"\rtrusted_cidrs\x18\x04 \x03(\tR\ftrustedCidrs\x12!\n" +
	"\fraw_fallback\x18\x05 \x01(\tR\vrawFallback\x12;\n" +
	"\x1araw_fallback_trusted_cidrs\x18\x06 \x03(\tR\x17rawFallbackTrustedCidrs\x129\n" +
	"\x19allow_public_raw_fallback\x18\a \x01(\bR\x16allowPublicRawFallback\"\xab\x01\n" +
	"\rTrafficRouter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\ventry_point\x18\x02 \x01(\tR\n" +
	"entryPoint\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12/\n" +
	"\x04rule\x18\x04 \x01(\v2\x1b.gordon.edge.v1.TrafficRuleR\x04rule\x12\x18\n" +
	"\aservice\x18\x05 \x01(\tR\aservice\"3\n" +
	"\vTrafficRule\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x10\n" +
	"\x03sni\x18\x02 \x01(\tR\x03sni\"`\n" +
	"\x0eTrafficService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12:\n" +
	"\bbackends\x18\x02 \x03(\v2\x1e.gordon.edge.v1.TrafficBackendR\bbackends\"h\n" +
	"\x0eTrafficBackend\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\"\xd1\x01\n" +
	"\x13RouteTargetSnapshot\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x12:\n" +
	"\aentries\x18\x02 \x03(\v2 .gordon.edge.v1.RouteTargetEntryR\aentries\x12^\n" +
	"\x1aregistry_forwarding_target\x18\x03 \x01(\v2 .gordon.edge.v1.RouteTargetEntryR\x18registryForwardingTarget\"\xfe\x02\n" +
	"\x10RouteTargetEntry\x12)\n" +
	"\x10canonical_domain\x18\x01 \x01(\tR\x0fcanonicalDomain\x12\x1f\n" +
	"\vtarget_host\x18\x02 \x01(\tR\n" +
	"targetHost\x12\x1f\n" +
	"\vtarget_port\x18\x03 \x01(\x05R\n" +
	"targetPort\x12\x16\n" +
	"\x06scheme\x18\x04 \x01(\tR\x06scheme\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12-\n" +
	"\x12unavailable_reason\x18\a \x01(\tR\x11unavailableReason\x12\x1e\n" +
	"\n" +
	"generation\x18\b \x01(\x04R\n" +
	"generation\x12#\n" +
	"\rupstream_host\x18\t \x01(\tR\fupstreamHost\x12\x1e\n" +
	"\n" +
	"attachment\x18\n" +
	" \x01(\tR\n" +
	"attachment\x12\x1d\n" +
	"\n" +
	"target_key\x18\v \x01(\tR\ttargetKey\"\xcc\x02\n" +
	"\x17ReportDrainStateRequest\x12)\n" +
	"\x10canonical_domain\x18\x01 \x01(\tR\x0fcanonicalDomain\x123\n" +
	"\x15transition_generation\x18\x02 \x01(\x04R\x14transitionGeneration\x12$\n" +
	"\x0eold_target_key\x18\x03 \x01(\tR\foldTargetKey\x12\x1b\n" +
	"\tin_flight\x18\x04 \x01(\x04R\binFlight\x12C\n" +
	"\x0facknowledged_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0eacknowledgedAt\x12I\n" +
	"\x0etimeout_reason\x18\x06 \x01(\x0e2\".gordon.edge.v1.DrainTimeoutReasonR\rtimeoutReason\"\x1a\n" +
	"\x18ReportDrainStateResponse\"\xb2\x01\n" +
	"\x19ReportAppliedStateRequest\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\x12)\n" +
	"\x10route_generation\x18\x02 \x01(\x04R\x0frouteGeneration\x12-\n" +
	"\x12traffic_generation\x18\x03 \x01(\x04R\x11trafficGeneration\x12\x18\n" +
	"\ahealthy\x18\x04 \x01(\bR\ahealthy\"\x1c\n" +
	"\x1aReportAppliedStateResponse*{\n" +
	"\x12DrainTimeoutReason\x12$\n" +
	" DRAIN_TIMEOUT_REASON_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19DRAIN_TIMEOUT_REASON_EDGE\x10\x01\x12 \n" +
	"\x1cDRAIN_TIMEOUT_REASON_CONTROL\x10\x022\xb4\x03\n" +
	"\vEdgeService\x12h\n" +
	"\x13WatchRouteSnapshots\x12*.gordon.edge.v1.WatchRouteSnapshotsRequest\x1a#.gordon.edge.v1.RouteTargetSnapshot0\x01\x12g\n" +
	"\x12WatchTrafficGraphs\x12).gordon.edge.v1.WatchTrafficGraphsRequest\x1a$.gordon.edge.v1.TrafficGraphSnapshot0\x01\x12e\n" +
	"\x10ReportDrainState\x12'.gordon.edge.v1.ReportDrainStateRequest\x1a(.gordon.edge.v1.ReportDrainStateResponse\x12k\n" +
	"\x12ReportAppliedState\x12).gordon.edge.v1.ReportAppliedStateRequest\x1a*.gordon.edge.v1.ReportAppliedStateResponseB3Z1github.com/bnema/gordon/api/gordon/edge/v1;edgev1b\x06proto3"

var (
	file_gordon_edge_v1_edge_proto_rawDescOnce sync.Once
	file_gordon_edge_v1_edge_proto_rawDescData []byte
)

func file_gordon_edge_v1_edge_proto_rawDescGZIP() []byte {
	file_gordon_edge_v1_edge_proto_rawDescOnce.Do(func() {
		file_gordon_edge_v1_edge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gordon_edge_v1_edge_proto_rawDesc), len(file_gordon_edge_v1_edge_proto_rawDesc)))
	})
	return file_gordon_edge_v1_edge_proto_rawDescData
}

var file_gordon_edge_v1_edge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gordon_edge_v1_edge_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_gordon_edge_v1_edge_proto_goTypes = []any{
	(DrainTimeoutReason)(0),            // 0: gordon.edge.v1.DrainTimeoutReason
	(*WatchRouteSnapshotsRequest)(nil), // 1: gordon.edge.v1.WatchRouteSnapshotsRequest
	(*WatchTrafficGraphsRequest)(nil),  // 2: gordon.edge.v1.WatchTrafficGraphsRequest
	(*TrafficGraphSnapshot)(nil),       // 3: gordon.edge.v1.TrafficGraphSnapshot
	(*TrafficOptions)(nil),             // 4: gordon.edge.v1.TrafficOptions
	(*TrafficTCPOptions)(nil),          // 5: gordon.edge.v1.TrafficTCPOptions
	(*TrafficUDPOptions)(nil),          // 6: gordon.edge.v1.TrafficUDPOptions
	(*TrafficEntryPoint)(nil),          // 7: gordon.edge.v1.TrafficEntryPoint
	(*TrafficRouter)(nil),              // 8: gordon.edge.v1.TrafficRouter
	(*TrafficRule)(nil),                // 9: gordon.edge.v1.TrafficRule
	(*TrafficService)(nil),             // 10: gordon.edge.v1.TrafficService
	(*TrafficBackend)(nil),             // 11: gordon.edge.v1.TrafficBackend
	(*RouteTargetSnapshot)(nil),        // 12: gordon.edge.v1.RouteTargetSnapshot
	(*RouteTargetEntry)(nil),           // 13: gordon.edge.v1.RouteTargetEntry
	(*ReportDrainStateRequest)(nil),    // 14: gordon.edge.v1.ReportDrainStateRequest
	(*ReportDrainStateResponse)(nil),   // 15: gordon.edge.v1.ReportDrainStateResponse
	(*ReportAppliedStateRequest)(nil),  // 16: gordon.edge.v1.ReportAppliedStateRequest
	(*ReportAppliedStateResponse)(nil), // 17: gordon.edge.v1.ReportAppliedStateResponse
	(*timestamppb.Timestamp)(nil),      // 18: google.protobuf.Timestamp
}
var file_gordon_edge_v1_edge_proto_depIdxs = []int32{
	4,  // 0: gordon.edge.v1.TrafficGraphSnapshot.options:type_name -> gordon.edge.v1.TrafficOptions
	7,  // 1: gordon.edge.v1.TrafficGraphSnapshot.entry_points:type_name -> gordon.edge.v1.TrafficEntryPoint
	8,  // 2: gordon.edge.v1.TrafficGraphSnapshot.routers:type_name -> gordon.edge.v1.TrafficRouter
	10, // 3: gordon.edge.v1.TrafficGraphSnapshot.services:type_name -> gordon.edge.v1.TrafficService
	5,  // 4: gordon.edge.v1.TrafficOptions.tcp:type_name -> gordon.edge.v1.TrafficTCPOptions
	6,  // 5: gordon.edge.v1.TrafficOptions.udp:type_name -> gordon.edge.v1.TrafficUDPOptions
	9,  // 6: gordon.edge.v1.TrafficRouter.rule:type_name -> gordon.edge.v1.TrafficRule
	11, // 7: gordon.edge.v1.TrafficService.backends:type_name -> gordon.edge.v1.TrafficBackend
	13, // 8: gordon.edge.v1.RouteTargetSnapshot.entries:type_name -> gordon.edge.v1.RouteTargetEntry
	13, // 9: gordon.edge.v1.RouteTargetSnapshot.registry_forwarding_target:type_name -> gordon.edge.v1.RouteTargetEntry
	18, // 10: gordon.edge.v1.ReportDrainStateRequest.acknowledged_at:type_name -> google.protobuf.Timestamp
	0,  // 11: gordon.edge.v1.ReportDrainStateRequest.timeout_reason:type_name -> gordon.edge.v1.DrainTimeoutReason
	1,  // 12: gordon.edge.v1.EdgeService.WatchRouteSnapshots:input_type -> gordon.edge.v1.WatchRouteSnapshotsRequest
	2,  // 13: gordon.edge.v1.EdgeService.WatchTrafficGraphs:input_type -> gordon.edge.v1.WatchTrafficGraphsRequest
	14, // 14: gordon.edge.v1.EdgeService.ReportDrainState:input_type -> gordon.edge.v1.ReportDrainStateRequest
	16, // 15: gordon.edge.v1.EdgeService.ReportAppliedState:input_type -> gordon.edge.v1.ReportAppliedStateRequest
	12, // 16: gordon.edge.v1.EdgeService.WatchRouteSnapshots:output_type -> gordon.edge.v1.RouteTargetSnapshot
	3,  // 17: gordon.edge.v1.EdgeService.WatchTrafficGraphs:output_type -> gordon.edge.v1.TrafficGraphSnapshot
	15, // 18: gordon.edge.v1.EdgeService.ReportDrainState:output_type -> gordon.edge.v1.ReportDrainStateResponse
	17, // 19: gordon.edge.v1.EdgeService.ReportAppliedState:output_type -> gordon.edge.v1.ReportAppliedStateResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_gordon_edge_v1_edge_proto_init() }
func file_gordon_edge_v1_edge_proto_init() {
	if File_gordon_edge_v1_edge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gordon_edge_v1_edge_proto_rawDesc), len(file_gordon_edge_v1_edge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gordon_edge_v1_edge_proto_goTypes,
		DependencyIndexes: file_gordon_edge_v1_edge_proto_depIdxs,
		EnumInfos:         file_gordon_edge_v1_edge_proto_enumTypes,
		MessageInfos:      file_gordon_edge_v1_edge_proto_msgTypes,
	}.Build()
	File_gordon_edge_v1_edge_proto = out.File
	file_gordon_edge_v1_edge_proto_goTypes = nil
	file_gordon_edge_v1_edge_proto_depIdxs = nil
}
