# Example GitHub Actions workflow for deploying to Gordon
# Copy this file to your repository as .github/workflows/deploy.yml
#
# Prerequisites:
# 1. Generate a Gordon token on your server:
#    gordon auth token generate --subject github-actions --scopes push,pull --expiry 0
#
# 2. Add these secrets to your GitHub repository:
#    - GORDON_REGISTRY: Your registry URL (e.g., registry.mydomain.com)
#    - GORDON_USERNAME: Token subject (e.g., github-actions)
#    - GORDON_TOKEN: The generated JWT token

name: Deploy to Gordon

on:
  # Deploy on version tags
  push:
    tags:
      - 'v*'        # Matches v1.0.0, v2.1.3, etc.
      - 'release-*' # Matches release-2024-01-15, etc.

  # Optional: Allow manual deployments
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag/version to deploy (leave empty for latest commit)'
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Optional: Only deploy from main branch for manual triggers
    # if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          # For manual dispatch with specific tag
          ref: ${{ github.event.inputs.tag || github.ref }}

      - name: Deploy to Gordon
        id: deploy
        uses: bnema/gordon/.github/actions/deploy@main
        with:
          registry: ${{ secrets.GORDON_REGISTRY }}
          username: ${{ secrets.GORDON_USERNAME }}
          password: ${{ secrets.GORDON_TOKEN }}
          tag: ${{ github.event.inputs.tag }}
          # Optional customizations:
          # image: myapp                    # Custom image name (defaults to repo name)
          # dockerfile: ./Dockerfile        # Custom Dockerfile path
          # context: .                      # Build context
          # push-latest: 'true'             # Also push :latest tag
          # platforms: linux/amd64          # Target platform(s)

      - name: Deployment summary
        run: |
          echo "## Deployment Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Image:** \`${{ steps.deploy.outputs.image }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Tag:** \`${{ steps.deploy.outputs.tag }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Gordon will automatically deploy this image to your configured routes." >> $GITHUB_STEP_SUMMARY

# ============================================================================
# ALTERNATIVE CONFIGURATIONS
# ============================================================================

# --- Deploy on push to main (continuous deployment) ---
#
# on:
#   push:
#     branches:
#       - main
#
# Then in the action, the image will be tagged with the commit SHA.

# --- Deploy multiple services (monorepo) ---
#
# jobs:
#   deploy-api:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v6
#       - uses: bnema/gordon/.github/actions/deploy@main
#         with:
#           registry: ${{ secrets.GORDON_REGISTRY }}
#           username: ${{ secrets.GORDON_USERNAME }}
#           password: ${{ secrets.GORDON_TOKEN }}
#           image: myapp-api
#           dockerfile: ./services/api/Dockerfile
#           context: ./services/api
#
#   deploy-web:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v6
#       - uses: bnema/gordon/.github/actions/deploy@main
#         with:
#           registry: ${{ secrets.GORDON_REGISTRY }}
#           username: ${{ secrets.GORDON_USERNAME }}
#           password: ${{ secrets.GORDON_TOKEN }}
#           image: myapp-web
#           dockerfile: ./services/web/Dockerfile
#           context: ./services/web

# --- Deploy with build arguments ---
#
# - uses: bnema/gordon/.github/actions/deploy@main
#   with:
#     registry: ${{ secrets.GORDON_REGISTRY }}
#     username: ${{ secrets.GORDON_USERNAME }}
#     password: ${{ secrets.GORDON_TOKEN }}
#     build-args: |
#       NODE_ENV=production
#       API_URL=https://api.example.com
#       BUILD_DATE=${{ github.event.head_commit.timestamp }}

# --- Multi-platform builds ---
#
# - uses: bnema/gordon/.github/actions/deploy@main
#   with:
#     registry: ${{ secrets.GORDON_REGISTRY }}
#     username: ${{ secrets.GORDON_USERNAME }}
#     password: ${{ secrets.GORDON_TOKEN }}
#     platforms: linux/amd64,linux/arm64
