// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: core.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreService_GetTarget_FullMethodName         = "/gordon.CoreService/GetTarget"
	CoreService_GetRoutes_FullMethodName         = "/gordon.CoreService/GetRoutes"
	CoreService_GetExternalRoutes_FullMethodName = "/gordon.CoreService/GetExternalRoutes"
	CoreService_NotifyImagePushed_FullMethodName = "/gordon.CoreService/NotifyImagePushed"
	CoreService_WatchRouteChanges_FullMethodName = "/gordon.CoreService/WatchRouteChanges"
)

// CoreServiceClient is the client API for CoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CoreService is the main orchestration service provided by gordon-core.
// It handles target resolution, route management, and registry event notifications.
type CoreServiceClient interface {
	// GetTarget resolves a domain to its proxy target (container or external route)
	GetTarget(ctx context.Context, in *GetTargetRequest, opts ...grpc.CallOption) (*GetTargetResponse, error)
	// GetRoutes returns all configured routes
	GetRoutes(ctx context.Context, in *GetRoutesRequest, opts ...grpc.CallOption) (*GetRoutesResponse, error)
	// GetExternalRoutes returns only external (non-container) routes
	GetExternalRoutes(ctx context.Context, in *GetExternalRoutesRequest, opts ...grpc.CallOption) (*GetExternalRoutesResponse, error)
	// NotifyImagePushed is called by the registry when an image is pushed
	NotifyImagePushed(ctx context.Context, in *NotifyImagePushedRequest, opts ...grpc.CallOption) (*NotifyImagePushedResponse, error)
	// WatchRouteChanges streams route change events for cache invalidation
	WatchRouteChanges(ctx context.Context, in *WatchRouteChangesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RouteChangeEvent], error)
}

type coreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreServiceClient(cc grpc.ClientConnInterface) CoreServiceClient {
	return &coreServiceClient{cc}
}

func (c *coreServiceClient) GetTarget(ctx context.Context, in *GetTargetRequest, opts ...grpc.CallOption) (*GetTargetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTargetResponse)
	err := c.cc.Invoke(ctx, CoreService_GetTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetRoutes(ctx context.Context, in *GetRoutesRequest, opts ...grpc.CallOption) (*GetRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutesResponse)
	err := c.cc.Invoke(ctx, CoreService_GetRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetExternalRoutes(ctx context.Context, in *GetExternalRoutesRequest, opts ...grpc.CallOption) (*GetExternalRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExternalRoutesResponse)
	err := c.cc.Invoke(ctx, CoreService_GetExternalRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) NotifyImagePushed(ctx context.Context, in *NotifyImagePushedRequest, opts ...grpc.CallOption) (*NotifyImagePushedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyImagePushedResponse)
	err := c.cc.Invoke(ctx, CoreService_NotifyImagePushed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) WatchRouteChanges(ctx context.Context, in *WatchRouteChangesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RouteChangeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoreService_ServiceDesc.Streams[0], CoreService_WatchRouteChanges_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRouteChangesRequest, RouteChangeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoreService_WatchRouteChangesClient = grpc.ServerStreamingClient[RouteChangeEvent]

// CoreServiceServer is the server API for CoreService service.
// All implementations should embed UnimplementedCoreServiceServer
// for forward compatibility.
//
// CoreService is the main orchestration service provided by gordon-core.
// It handles target resolution, route management, and registry event notifications.
type CoreServiceServer interface {
	// GetTarget resolves a domain to its proxy target (container or external route)
	GetTarget(context.Context, *GetTargetRequest) (*GetTargetResponse, error)
	// GetRoutes returns all configured routes
	GetRoutes(context.Context, *GetRoutesRequest) (*GetRoutesResponse, error)
	// GetExternalRoutes returns only external (non-container) routes
	GetExternalRoutes(context.Context, *GetExternalRoutesRequest) (*GetExternalRoutesResponse, error)
	// NotifyImagePushed is called by the registry when an image is pushed
	NotifyImagePushed(context.Context, *NotifyImagePushedRequest) (*NotifyImagePushedResponse, error)
	// WatchRouteChanges streams route change events for cache invalidation
	WatchRouteChanges(*WatchRouteChangesRequest, grpc.ServerStreamingServer[RouteChangeEvent]) error
}

// UnimplementedCoreServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreServiceServer struct{}

func (UnimplementedCoreServiceServer) GetTarget(context.Context, *GetTargetRequest) (*GetTargetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTarget not implemented")
}
func (UnimplementedCoreServiceServer) GetRoutes(context.Context, *GetRoutesRequest) (*GetRoutesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoutes not implemented")
}
func (UnimplementedCoreServiceServer) GetExternalRoutes(context.Context, *GetExternalRoutesRequest) (*GetExternalRoutesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExternalRoutes not implemented")
}
func (UnimplementedCoreServiceServer) NotifyImagePushed(context.Context, *NotifyImagePushedRequest) (*NotifyImagePushedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyImagePushed not implemented")
}
func (UnimplementedCoreServiceServer) WatchRouteChanges(*WatchRouteChangesRequest, grpc.ServerStreamingServer[RouteChangeEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchRouteChanges not implemented")
}
func (UnimplementedCoreServiceServer) testEmbeddedByValue() {}

// UnsafeCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServiceServer will
// result in compilation errors.
type UnsafeCoreServiceServer interface {
	mustEmbedUnimplementedCoreServiceServer()
}

func RegisterCoreServiceServer(s grpc.ServiceRegistrar, srv CoreServiceServer) {
	// If the following call pancis, it indicates UnimplementedCoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreService_ServiceDesc, srv)
}

func _CoreService_GetTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetTarget(ctx, req.(*GetTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetRoutes(ctx, req.(*GetRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetExternalRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExternalRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetExternalRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetExternalRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetExternalRoutes(ctx, req.(*GetExternalRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_NotifyImagePushed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyImagePushedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).NotifyImagePushed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_NotifyImagePushed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).NotifyImagePushed(ctx, req.(*NotifyImagePushedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_WatchRouteChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRouteChangesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoreServiceServer).WatchRouteChanges(m, &grpc.GenericServerStream[WatchRouteChangesRequest, RouteChangeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoreService_WatchRouteChangesServer = grpc.ServerStreamingServer[RouteChangeEvent]

// CoreService_ServiceDesc is the grpc.ServiceDesc for CoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gordon.CoreService",
	HandlerType: (*CoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTarget",
			Handler:    _CoreService_GetTarget_Handler,
		},
		{
			MethodName: "GetRoutes",
			Handler:    _CoreService_GetRoutes_Handler,
		},
		{
			MethodName: "GetExternalRoutes",
			Handler:    _CoreService_GetExternalRoutes_Handler,
		},
		{
			MethodName: "NotifyImagePushed",
			Handler:    _CoreService_NotifyImagePushed_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchRouteChanges",
			Handler:       _CoreService_WatchRouteChanges_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "core.proto",
}
