// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Footer is a templ component for the page footer
// It replaces footer.gohtml
func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"footer p-10 bg-base-200 text-base-content\"><div><span class=\"footer-title\">Gordon</span> <a class=\"link link-hover\">About us</a> <a class=\"link link-hover\">Documentation</a> <a class=\"link link-hover\">Github</a></div><div><span class=\"footer-title\">Container Management</span> <a class=\"link link-hover\">Dashboard</a> <a class=\"link link-hover\">Settings</a> <a class=\"link link-hover\">Stats</a></div><div><span class=\"footer-title\">Legal</span> <a class=\"link link-hover\">Terms of use</a> <a class=\"link link-hover\">Privacy policy</a> <a class=\"link link-hover\">License</a></div></footer><footer class=\"footer px-10 py-4 border-t bg-base-300 text-base-content border-base-300\"><div class=\"items-center grid-flow-col\"><span class=\"iconfb text-2xl\">\U000f02a2</span><p class=\"IBMPlexSans\">Gordon Container Manager<br>Providing reliable container management since 2023</p></div><div class=\"md:place-self-center md:justify-self-end\"><div class=\"grid grid-flow-col gap-4\"><a class=\"iconfb text-2xl\">\U000f02a4</a> <a class=\"iconfb text-2xl\">\U000f05c3</a> <a class=\"iconfb text-2xl\">\U000f059f</a></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
