name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist --clean

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: Build and push Docker images
        run: |
          go build -o gordon ./cmd/cli/main.go
          docker build -t ghcr.io/bnema/gordon:${{ github.ref_name }}-amd64 --build-arg BINARY=gordon --platform=linux/amd64 .
          docker build -t ghcr.io/bnema/gordon:${{ github.ref_name }}-arm64 --build-arg BINARY=gordon --platform=linux/arm64 .
          docker push ghcr.io/bnema/gordon:${{ github.ref_name }}-amd64
          docker push ghcr.io/bnema/gordon:${{ github.ref_name }}-arm64
          
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
