name: Release

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --clean

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Install Cosign
        run: |
          curl -sfL https://raw.githubusercontent.com/sigstore/cosign/main/install.sh | sudo sh

      - name: Copy dist directory
        run: |
          mkdir -p docker-build
          cp -r dist docker-build/
          cp Dockerfile docker-build/

      - name: Build and push Docker images
        run: |
          docker build -t ghcr.io/bnema/gordon:${{ github.ref_name }}-amd64 --build-arg BINARY=gordon_linux_amd64/gordon --platform=linux/amd64 docker-build
          docker build -t ghcr.io/bnema/gordon:${{ github.ref_name }}-arm64 --build-arg BINARY=gordon_linux_arm64/gordon --platform=linux/arm64 docker-build
          docker push ghcr.io/bnema/gordon:${{ github.ref_name }}-amd64
          docker push ghcr.io/bnema/gordon:${{ github.ref_name }}-arm64

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
